import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,rmSync,copyFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname,basename} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {unzipSync} from 'fflate';
import {Store} from '../electron/core/store';
import {DesignStore} from '../electron/core/design-store';
import {DesignerFiles} from '../electron/core/designer-files';
import {DesignFonts} from '../electron/core/design-fonts';
import {applyDesignFont} from '../electron/core/design-font-application';
import {DesignerLoop} from '../electron/core/designer-loop';
import {Harness} from '../electron/core/harness';
import {ArtifactService} from '../electron/core/artifacts';
import {Attachments} from '../electron/core/attachments';
import {AgentPreviews} from '../electron/core/agent-previews';
const fixture=(t:test.TestContext)=>{
 const root=mkdtempSync(join(tmpdir(),'aelion-font-flow-'));t.after(()=>{assert.equal(dirname(resolve(root)),resolve(tmpdir()));assert.ok(basename(root).startsWith('aelion-font-flow-'));rmSync(root,{recursive:true,force:true});});
 const store=new Store(join(root,'data'));t.after(()=>store.close());const bot=store.createBot('Designer','',undefined,undefined,{type:'designer'});store.data.model.model='test';
 const designs=new DesignStore(store,{} as any,()=>{},()=>join(root,'workspace')),session=designs.create({botId:bot.id,kind:'prototype',brief:'Font test'}),files=new DesignerFiles(store,designs),fonts=new DesignFonts({cacheDir:join(root,'cache'),files,fetch:async()=>{throw Error('offline test');}});
 const source=resolve('node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2');mkdirSync(join(session.workspaceDir!,'assets'),{recursive:true});copyFileSync(source,join(session.workspaceDir!,'assets/source.woff2'));
 return {root,store,bot,designs,session:designs.get(session.id),files,fonts,fontPath:join(session.workspaceDir!,'assets/source.woff2')};
};
test('font application preserves source and ignores managed markers and head strings inside scripts/templates',async t=>{
 const f=fixture(t),[font]=await f.fonts.importFile(f.session,f.fontPath);
 const script='<script>const sample="<!-- aelion:project-fonts --><!-- /aelion:project-fonts -->";const head="</head>";</script>',template='<template><!-- aelion:project-fonts -->sample<!-- /aelion:project-fonts --></template>';
 const html='<!doctype html>\r\n<html><head>'+script+'<style>.hero{font-family:serif}</style></head><body>'+template+'<h1 class="hero" style="font-family:Arial">Hello</h1><p>Content</p></body></html>';
 f.files.write(f.session,'pages/index.html',Buffer.from(html));
 await applyDesignFont(f.files,f.session,f.fonts.list(f.session),{fontId:font.id,role:'display',path:'pages/index.html'});
 const first=readFileSync(f.files.absolute(f.session,'pages/index.html'),'utf8');assert.ok(first.includes(script));assert.ok(first.includes(template));assert.ok(first.startsWith('<!doctype html>\r\n'));assert.match(first,/href="\.\.\/assets\/fonts\/fonts.css"/);assert.match(first,/font-family:var\(--font-display\)!important/);
 await applyDesignFont(f.files,f.session,f.fonts.list(f.session),{fontId:font.id,role:'body',path:'pages/index.html'});
 const second=readFileSync(f.files.absolute(f.session,'pages/index.html'),'utf8');assert.equal((second.match(/data-font-roles=/g)||[]).length,1);assert.match(second,/--font-display/);assert.match(second,/--font-body/);assert.ok(second.includes(script));assert.ok(second.includes(template));
 await assert.rejects(applyDesignFont(f.files,f.session,f.fonts.list(f.session),{fontId:font.id,role:'mono',path:'pages/index.html'},()=>{throw Error('cancelled');}),/cancelled/);assert.equal(readFileSync(f.files.absolute(f.session,'pages/index.html'),'utf8'),second);
 await assert.rejects(applyDesignFont(f.files,f.session,f.fonts.list(f.session),{fontId:font.id,role:'body',path:'../outside.html'}));
});
test('designer tools import, apply and export actual project font bytes after permission',async t=>{
 const f=fixture(t);f.files.write(f.session,'index.html',Buffer.from('<html><head><style>body{margin:20px;color:#242424}h1{font-size:32px}</style></head><body><h1>Typography</h1><p>Local font delivery</p></body></html>'));
 const vm=new Proxy({},{get(){throw Error('No VM access');}}),artifacts=new ArtifactService(f.store,vm as any);artifacts.designerFiles=f.files;
 const attachments=new Attachments(f.store,vm as any,artifacts),permissions:Array<{operation:string;path:string}>=[];
 const interactions={permission:async(_bot:string,_run:string,input:any)=>{permissions.push(input);},pendingQuestions:()=>[],cancelQuestions:()=>{}};
 const fontId='import-'+createHash('sha256').update(readFileSync(f.fontPath)).digest('hex').slice(0,16);
 const calls=[['design_fonts',{action:'import',path:'assets/source.woff2',reason:'Use provided font'}],['design_font_apply',{fontId,role:'display',path:'index.html',reason:'Apply heading font'}],['design_export_pdf',{path:'index.html',output:'design.pdf',reason:'Export PDF'}],['design_export_project',{path:'index.html',output:'site.zip',reason:'Export portable design'}],['design_publish',{paths:['index.html','design.pdf']}]];
 let turn=0,printed='';const model={complete:async()=>({content:'Font project ready',calls:turn<calls.length?(()=>{const [name,args]=calls[turn++] as [string,unknown];return [{id:randomUUID(),type:'function',function:{name,arguments:JSON.stringify(args)}}];})():[],finishReason:'stop'})};
 const shared=new Harness(f.store,vm as any,model as any,()=>{},undefined,undefined,undefined,undefined,interactions as any,undefined,attachments);t.after(()=>shared.disposeTools());
 shared.setPreviewGateway(new AgentPreviews(f.store,artifacts,attachments,()=>{}));
 const context={observe:()=>{},prepare:async(input:any)=>({messages:[input.system,...input.history],maxOutputTokens:8192,stats:{calibration:1},calibrationEstimate:2000,recordUsage:()=>{}})};
 const loop=new DesignerLoop(f.store,f.designs,{} as any,f.files,model as any,context as any,shared,artifacts,attachments,interactions as any,()=>{},{fonts:f.fonts,pdf:{render:async html=>{printed=html;return Buffer.from('%PDF-1.7\nfixture');}}});
 await loop.run(f.bot.id,'Use this font and export the design',{designSessionId:f.session.id});
 const run=f.store.data.runs.at(-1)!;assert.equal(run.status,'completed',run.error||'Design run failed');assert.ok(permissions.some(p=>p.operation==='read_file'&&p.path===f.fontPath));assert.ok(permissions.some(p=>p.operation==='write_file'&&p.path.endsWith('fonts')));
 const encoded=printed.match(/href="data:text\/css;base64,([^"]+)"/)?.[1];assert.ok(encoded,'PDF must include font stylesheet');assert.ok(Buffer.from(encoded,'base64').toString().includes('data:font/woff2;base64,'),'PDF stylesheet must embed real font bytes');assert.match(printed,/--font-display/);const zip=unzipSync(readFileSync(f.files.absolute(f.session,'site.zip')));assert.ok(Object.keys(zip).some(path=>path.endsWith('.woff2')));assert.ok(Object.keys(zip).some(path=>path.endsWith('LICENSE.txt')));assert.ok(!zip['assets/source.woff2'],'unreferenced original font must not be bundled');
});
test('denied font import has no project font side effect',async t=>{
 const f=fixture(t),vm={} as any,artifacts=new ArtifactService(f.store,vm),attachments=new Attachments(f.store,vm,artifacts);artifacts.designerFiles=f.files;
 let turn=0;const model={complete:async()=>({content:'Cannot import',calls:turn++===0?[{id:randomUUID(),type:'function',function:{name:'design_fonts',arguments:JSON.stringify({action:'import',path:'assets/source.woff2',reason:'Import'})}}]:[],finishReason:'stop'})};
 const interactions={permission:async()=>{throw Error('Denied');},pendingQuestions:()=>[],cancelQuestions:()=>{}};
 const shared=new Harness(f.store,vm,model as any,()=>{},undefined,undefined,undefined,undefined,interactions as any,undefined,attachments);t.after(()=>shared.disposeTools());
 const context={observe:()=>{},prepare:async(input:any)=>({messages:[input.system,...input.history],maxOutputTokens:8192,stats:{calibration:1},calibrationEstimate:2000,recordUsage:()=>{}})};
 const loop=new DesignerLoop(f.store,f.designs,{} as any,f.files,model as any,context as any,shared,artifacts,attachments,interactions as any,()=>{},{fonts:f.fonts});await loop.run(f.bot.id,'Import font',{designSessionId:f.session.id});assert.deepEqual(f.fonts.list(f.session),[]);
 assert.ok(f.store.data.runs.at(-1)?.executions?.some(item=>item.tool==='design_fonts'&&item.status==='failed'));
});

test('active designer autonomously searches, downloads and applies an open-source font through its tools',async t=>{
 const f=fixture(t),downloads:string[]=[],permissions:string[]=[];
 const metadata={id:'inter',family:'Inter',category:'sans-serif',weights:[400],styles:['normal'],subsets:['latin'],defSubset:'latin',license:{type:'OFL-1.1'}};
 const fonts=new DesignFonts({cacheDir:join(f.root,'remote-cache'),files:f.files,fetch:async(input,init)=>{
  const url=String(input);downloads.push(url);assert.equal(init?.credentials,'omit');
  if(url.endsWith('/v1/fonts'))return Response.json([metadata]);
  assert.ok(permissions.length>0,'downloading font assets requires the task write permission first');
  if(url.endsWith('/v1/version/inter'))return Response.json({latest:'5.3.0'});
  if(url.endsWith('/metadata.json'))return Response.json(metadata);
  if(url.endsWith('/LICENSE'))return new Response('SIL OPEN FONT LICENSE Version 1.1');
  if(url.endsWith('/400.css'))return new Response("/* inter-latin-400-normal */\n@font-face{font-family:'Inter';font-weight:400;src:url(./files/inter-latin-400-normal.woff2) format('woff2');unicode-range:U+0000-00FF;}");
  if(url.endsWith('/inter-latin-400-normal.woff2'))return new Response(new Uint8Array(readFileSync(f.fontPath)));
  throw Error('Unexpected request '+url);
 }});
 f.files.write(f.session,'index.html',Buffer.from('<html><head><title>Type</title></head><body><h1>Hello</h1></body></html>'));
 const vm=new Proxy({},{get(){throw Error('No VM access');}}),artifacts=new ArtifactService(f.store,vm as any);artifacts.designerFiles=f.files;
 const attachments=new Attachments(f.store,vm as any,artifacts),interactions={permission:async(_bot:string,_run:string,input:any)=>{permissions.push(input.path);},pendingQuestions:()=>[],cancelQuestions:()=>{}};
 let step=0;const model={complete:async(messages:any[],tools:any[])=>{
  assert.ok(tools.some(tool=>tool.function.name==='design_fonts'));
  if(step>0&&step<5)assert.ok(messages.some(message=>message.role==='tool'),'next decision receives the preceding tool result');
  const added=fonts.list(f.session)[0];
  const calls=[['design_fonts',{action:'search',query:'Inter'}],['design_fonts',{action:'acquire',fontId:metadata.id,weights:[400],reason:'Use a readable heading font'}],['design_font_apply',{fontId:added?.id,role:'display',path:'index.html',reason:'Apply the downloaded font'}],['design_fonts',{action:'check',family:'Inter',text:'Hello'}],['design_publish',{paths:['index.html']}]];
  const next=calls[step++] as [string,unknown]|undefined;
  return {content:'Typography ready',calls:next?[{id:randomUUID(),type:'function',function:{name:next[0],arguments:JSON.stringify(next[1])}}]:[],finishReason:'stop'};
 }};
 const shared=new Harness(f.store,vm as any,model as any,()=>{},undefined,undefined,undefined,undefined,interactions as any,undefined,attachments);t.after(()=>shared.disposeTools());shared.setPreviewGateway(new AgentPreviews(f.store,artifacts,attachments,()=>{}));
 const context={observe:()=>{},prepare:async(input:any)=>({messages:[input.system,...input.history],maxOutputTokens:8192,stats:{calibration:1},calibrationEstimate:2000,recordUsage:()=>{}})};
 const loop=new DesignerLoop(f.store,f.designs,{} as any,f.files,model as any,context as any,shared,artifacts,attachments,interactions as any,()=>{},{fonts});
 await loop.run(f.bot.id,'Design a readable page and choose a suitable open-source font',{designSessionId:f.session.id});
 const run=f.store.data.runs.at(-1)!;assert.equal(run.status,'completed',run.error||'Designer task failed');
 const [font]=fonts.list(f.session);assert.equal(font.source,'fontsource');assert.equal(font.family,'Inter');assert.equal(font.available,true);assert.ok(downloads.some(url=>url.endsWith('.woff2')));
 assert.match(readFileSync(f.files.absolute(f.session,'index.html'),'utf8'),/--font-display:"Inter"/);assert.match(readFileSync(f.files.absolute(f.session,font.cssPath),'utf8'),/\.woff2/);
 assert.ok(!run.executions?.some(execution=>execution.tool==='request_user_input'),'font selection does not require a separate user question');
 assert.deepEqual(fonts.check(f.session,{text:'Hello'}).fonts[0].missingCharacters,[]);
});
