import test from 'node:test';import assert from 'node:assert/strict';import {createServer,type ServerResponse} from 'node:http';import {ModelClient} from '../electron/core/model';
const event=(res:ServerResponse,data:unknown)=>res.write('data: '+JSON.stringify(data)+'\n\n');
async function fixture(t:any,handle:(res:ServerResponse)=>void,protocol='chat'){const server=createServer(async(req,res)=>{for await(const _ of req){}res.writeHead(200,{'content-type':'text/event-stream'});handle(res);});await new Promise<void>(done=>server.listen(0,'127.0.0.1',done));const model=new ModelClient(()=>({baseUrl:`http://127.0.0.1:${(server.address() as any).port}/v1`,model:'test',contextTokens:128000,hasKey:false,protocol} as any),()=> '');t.after(()=>{model.dispose();server.closeAllConnections();server.close();});return model;}
test('continuous tool-argument output may exceed the inactivity timeout without being discarded',async t=>{const model=await fixture(t,res=>{event(res,{choices:[{delta:{tool_calls:[{index:0,id:'call-1',type:'function',function:{name:'file_write',arguments:'{"content":"'}}]}}]});let n=0;const timer=setInterval(()=>{if(++n<=10)event(res,{choices:[{delta:{tool_calls:[{index:0,function:{arguments:'part'}}]}}]});else{clearInterval(timer);event(res,{choices:[{delta:{tool_calls:[{index:0,function:{arguments:'"}'}}]},finish_reason:'tool_calls'}]});event(res,{choices:[],usage:{prompt_tokens:20,completion_tokens:40,total_tokens:60}});res.end('data: [DONE]\n\n');}},45);res.on('close',()=>clearInterval(timer));});const statuses:any[]=[];const result=await model.complete([{role:'user',content:'Write a file'}],[],new AbortController().signal,()=>{},{timeoutMs:220,retries:0,onStatus:s=>statuses.push(s)});assert.equal(JSON.parse(result.calls[0].function.arguments).content,'part'.repeat(10));assert.equal(result.usage?.outputTokens,40);assert.ok(statuses.some(s=>s.activity==='tool'));});
test('finished Chat response retains trailing usage and does not wait forever for DONE',async t=>{const model=await fixture(t,res=>{event(res,{choices:[{delta:{content:'Complete'},finish_reason:'stop'}]});setTimeout(()=>event(res,{choices:[],usage:{prompt_tokens:12,completion_tokens:3,total_tokens:15}}),30);});const result=await model.complete([],[],new AbortController().signal,()=>{},{timeoutMs:150,retries:0});assert.equal(result.content,'Complete');assert.equal(result.usage?.totalTokens,15);});
test('heartbeat-only streams still time out',async t=>{const model=await fixture(t,res=>{const timer=setInterval(()=>res.write(': ping\n\n'),20);res.on('close',()=>clearInterval(timer));});await assert.rejects(model.complete([],[],new AbortController().signal,()=>{},{timeoutMs:120,retries:0}),/timeout|超时/i);});
test('SSE multiline data and bare carriage-return boundaries are parsed as complete events',async t=>{const model=await fixture(t,res=>{res.end('data: {"choices":\rdata: [{"delta":{"content":"完整"},"finish_reason":"stop"}]}\r\rdata: [DONE]\r\r');});const result=await model.complete([],[],new AbortController().signal,()=>{},{timeoutMs:200,retries:0});assert.equal(result.content,'完整');});
test('completion marker never authorizes incomplete tool JSON',async t=>{const model=await fixture(t,res=>{event(res,{choices:[{delta:{tool_calls:[{index:0,id:'broken',type:'function',function:{name:'file_write',arguments:'{"content":'}}]},finish_reason:'tool_calls'}]});res.end('data: [DONE]\n\n');});const result=await model.complete([],[],new AbortController().signal,()=>{},{timeoutMs:200,retries:0});assert.equal(result.calls[0].function.name,'file_write');assert.throws(()=>JSON.parse(result.calls[0].function.arguments));});

for(const protocol of ['anthropic','responses','gemini'])test(`${protocol} meaningful non-text progress keeps a healthy long response alive`,async t=>{
 const model=await fixture(t,res=>{if(protocol==='anthropic'){event(res,{type:'message_start',message:{usage:{input_tokens:12}}});event(res,{type:'content_block_start',index:0,content_block:{type:'tool_use',id:'tool-1',name:'file_write',input:{}}});event(res,{type:'content_block_delta',index:0,delta:{type:'input_json_delta',partial_json:'{"content":"'}});}let n=0;const timer=setInterval(()=>{if(++n<=8){if(protocol==='anthropic')event(res,{type:'content_block_delta',index:0,delta:{type:'input_json_delta',partial_json:'x'}});if(protocol==='responses')event(res,{type:'response.function_call_arguments.delta',delta:'x'});if(protocol==='gemini')event(res,{candidates:[{content:{parts:[{text:'internal',thought:true}]}}]});return;}clearInterval(timer);if(protocol==='anthropic'){event(res,{type:'content_block_delta',index:0,delta:{type:'input_json_delta',partial_json:'"}'}});event(res,{type:'message_delta',delta:{stop_reason:'tool_use'},usage:{output_tokens:8}});event(res,{type:'message_stop'});}if(protocol==='responses')event(res,{type:'response.completed',response:{output:[{type:'function_call',call_id:'tool-1',name:'file_write',arguments:'{"content":"xxxxxxxx"}'}],usage:{input_tokens:12,output_tokens:8}}});if(protocol==='gemini')event(res,{candidates:[{content:{parts:[{functionCall:{name:'file_write',args:{content:'xxxxxxxx'}}}]},finishReason:'STOP'}],usageMetadata:{promptTokenCount:12,candidatesTokenCount:8}});res.end();},40);res.on('close',()=>clearInterval(timer));},protocol);
 const result=await model.complete([],[],new AbortController().signal,()=>{},{timeoutMs:180,retries:0});assert.equal(result.calls[0].function.name,'file_write');assert.equal(JSON.parse(result.calls[0].function.arguments).content,'xxxxxxxx');assert.equal(result.content,'');
});
test('role-only JSON frames cannot keep a stalled request alive',async t=>{const model=await fixture(t,res=>{const timer=setInterval(()=>event(res,{choices:[{delta:{role:'assistant'}}]}),25);res.on('close',()=>clearInterval(timer));});await assert.rejects(model.complete([],[],new AbortController().signal,()=>{},{timeoutMs:120,retries:0}),/超时/);});
test('user cancellation interrupts a continuously active stream',async t=>{const model=await fixture(t,res=>{const timer=setInterval(()=>event(res,{choices:[{delta:{content:'x'}}]}),25);res.on('close',()=>clearInterval(timer));});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(Error('user stopped')),140);try{await assert.rejects(model.complete([],[],controller.signal,()=>{},{timeoutMs:300,retries:0,onReset:()=>{}}),/user stopped/);}finally{clearTimeout(timer);}});
