import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,existsSync,rmSync,realpathSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname,resolve} from 'node:path';import {randomUUID} from 'node:crypto';
import {Store} from '../electron/core/store';import {HostComputer} from '../electron/core/host';import {Interactions} from '../electron/core/interactions';import {Harness} from '../electron/core/harness';import type {ModelClient} from '../electron/core/model';import type {WireMessage} from '../src/shared';
const call=(name:string,args:unknown)=>({id:randomUUID(),type:'function' as const,function:{name,arguments:JSON.stringify(args)}});
for(const automatic of [false,true])for(const nested of [false,true])test(`${automatic?'model':'human'} denial ${nested?'inside code_exec':'in a tool batch'} returns to the model without running the denied operation`,async t=>{
 const parent=realpathSync(tmpdir()),dir=mkdtempSync(join(parent,'aelion-denied-flow-')),store=new Store(join(dir,'data')),bot=store.data.bots[0];store.data.model.model='test';store.data.model.contextTokens=64000;writeFileSync(join(dir,'safe.txt'),'allowed content');
 const interactions=new Interactions(()=>{if(!automatic)for(const request of interactions.snapshot())if(request.kind==='host_permission')queueMicrotask(()=>{try{interactions.approve(request.id,!request.details.path?.endsWith('denied.txt'));}catch{}});});
 if(automatic)interactions.setHostPolicy({modeFor:()=> 'auto',assess:request=>request.details.path?.endsWith('denied.txt')?{kind:'review',mode:'auto',reason:'review'}:{kind:'allow',mode:'auto',source:'low-risk',reason:'allowed'},review:async()=>({decision:'deny',reason:'Requested write is outside the authorized task'})});
 const host=new HostComputer({dataDir:store.dir,homeDir:dir,projectDir:dir},interactions);let turns=0;
 const model={complete:async(messages:WireMessage[])=>{
  if(++turns===1){const denied={path:'denied.txt',content:'blocked',reason:'write'},after={path:'after.txt',content:'must not run',reason:'write'};return {content:'',finishReason:'tool_calls',calls:nested?[call('code_exec',{code:`await tools.host_file_read({path:'safe.txt',reason:'read'});await tools.host_file_write(${JSON.stringify(denied)});await tools.host_file_write(${JSON.stringify(after)});`})]:[call('host_file_write',denied),call('host_file_write',after)]};}
  if(turns===2){const denied=messages.filter(m=>m.role==='tool').map(m=>JSON.parse(m.content||'{}')).find(m=>m.result?.denied)?.result;assert.ok(denied);assert.match(denied.operationDenial.path,/denied.txt$/);assert.equal(denied.operationDenial.source,automatic?'model':'user');assert.match(denied.next,/Do not retry/);assert.equal(existsSync(join(dir,'denied.txt')),false);assert.equal(existsSync(join(dir,'after.txt')),false);if(nested)assert.equal(denied.earlierOperationsMayHaveCompleted,true);return {content:'拒绝已收到，继续查看允许读取的文件。',finishReason:'tool_calls',calls:[call('host_file_read',{path:'safe.txt',reason:'continue allowed work'})]};}
  assert.ok(messages.some(m=>m.role==='tool'&&m.content?.includes('allowed content')));return {content:'已完成允许的读取；被拒绝的修改未执行。',finishReason:'stop',calls:[]};
 }} as unknown as ModelClient;
 const harness=new Harness(store,{} as any,model,()=>{},undefined,undefined,undefined,host,interactions);
 t.after(()=>{harness.disposeTools();interactions.dispose();host.dispose();store.close();assert.equal(dirname(resolve(dir)),parent);rmSync(dir,{recursive:true,force:true});});
 await harness.run(bot.id,'Read permitted files and explain unavailable changes',{workspaceDir:dir});assert.equal(turns,3);assert.equal(store.data.runs[0].status,'completed',store.data.runs[0].error||'');const notice=store.data.messages.find(m=>m.operationDenial);assert.ok(notice);assert.match(notice.operationDenial!.path!,/denied.txt$/);assert.equal(store.data.runs[0].executions?.some(e=>e.status==='succeeded'&&e.tool==='host_file_write'),false);
});
