import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,readFileSync,readdirSync,rmSync,realpathSync,mkdirSync,utimesSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';
import {VideoFrames} from '../electron/core/video-frames';import {videoFrameRequest,videoSampleTimes,videoFrameLayout} from '../src/video-frames';import type {HostComputer} from '../electron/core/host';import type {Attachments} from '../electron/core/attachments';
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS1sAAAAASUVORK5CYII=';
function fixture(t:test.TestContext){const parent=realpathSync(tmpdir()),dir=mkdtempSync(join(parent,'aelion-video-test-')),source=join(dir,'source.mp4');writeFileSync(source,'fixture source');t.after(()=>{assert.equal(dirname(dir),parent);rmSync(dir,{recursive:true,force:true});});return {dir,source};}
const sheet={dataUrl:png,width:320,height:202,duration:2,videoWidth:320,videoHeight:180,timestamps:[.5]};
test('sampling handles explicit points, bounded ranges and single-frame requests',()=>{assert.deepEqual(videoSampleTimes(10,{count:1}),[4.975]);assert.deepEqual(videoSampleTimes(10,{timestamps:[1,5,9]}),[1,5,9]);assert.equal(videoSampleTimes(10,{}).length,12);assert.throws(()=>videoFrameRequest({count:25}));assert.throws(()=>videoFrameRequest({timestamps:[1],count:1}));assert.throws(()=>videoSampleTimes(10,{timestamps:[10]}));assert.throws(()=>videoSampleTimes(Infinity,{}));assert.throws(()=>videoSampleTimes(10,{startSeconds:9,endSeconds:8}));});
test('contact sheets reuse cached images while permission checks still run and sources remain untouched',async t=>{const f=fixture(t);let reads=0,renders=0;const host={videoFile:async()=>{reads++;return f.source;}} as unknown as HostComputer;const service=new VideoFrames(host,{} as Attachments,join(f.dir,'images'),async()=>{renders++;return sheet;});const args={path:f.source,count:1,reason:'Inspect the video'},signal=new AbortController().signal;const first=await service.inspect('bot','run',args,signal),second=await service.inspect('bot','run',args,signal);assert.equal(first.cached,false);assert.equal(second.cached,true);assert.equal(renders,1);assert.equal(reads,2);assert.equal(first.images[0].id,second.images[0].id);assert.equal(readFileSync(f.source,'utf8'),'fixture source');assert.equal(readdirSync(join(f.dir,'images')).filter(n=>n.endsWith('.png')).length,1);});
test('changed video data cannot produce a cached or trusted frame result',async t=>{const f=fixture(t);const service=new VideoFrames({videoFile:async()=>f.source} as unknown as HostComputer,{} as Attachments,join(f.dir,'images'),async()=>{writeFileSync(f.source,'changed while decoding');return sheet;});await assert.rejects(service.inspect('bot','run',{path:f.source,reason:'inspect'},new AbortController().signal),/发生变化/);assert.equal(readdirSync(join(f.dir,'images')).filter(n=>n.endsWith('.png')).length,0);});
test('attachment authorization cannot be bypassed with another attachment ID',async t=>{const f=fixture(t);let renders=0;const service=new VideoFrames({} as HostComputer,{videoReference:()=>{throw Error('cannot read unreceived attachment');}} as unknown as Attachments,join(f.dir,'images'),async()=>{renders++;return sheet;});await assert.rejects(service.inspect('bot','run',{attachmentId:'foreign',reason:'inspect'},new AbortController().signal),/unreceived/);assert.equal(renders,0);});
test('a cancelled queued inspection returns immediately and never decodes',async t=>{const f=fixture(t);let finish!:(value:typeof sheet)=>void,renders=0;const service=new VideoFrames({videoFile:async()=>f.source} as unknown as HostComputer,{} as Attachments,join(f.dir,'images'),async()=>{renders++;return new Promise(resolve=>{finish=resolve;});});const first=service.inspect('bot','run',{path:f.source,reason:'first'},new AbortController().signal);await new Promise(r=>setTimeout(r,10));const controller=new AbortController();const second=service.inspect('other','run',{path:f.source,reason:'second'},controller.signal);controller.abort(Error('cancelled'));await assert.rejects(second,/cancelled/);finish(sheet);await first;await new Promise(r=>setTimeout(r,10));assert.equal(renders,1);});


test('unindexed cached images still count toward storage limits and retained images survive cleanup',async t=>{const f=fixture(t),images=join(f.dir,'images');mkdirSync(images);const retained=new Set<string>();for(let n=0;n<128;n++){const hex=n.toString(16).padStart(32,'0'),id=hex.slice(0,8)+'-'+hex.slice(8,12)+'-'+hex.slice(12,16)+'-'+hex.slice(16,20)+'-'+hex.slice(20);writeFileSync(join(images,id+'.png'),'cached');utimesSync(join(images,id+'.png'),new Date(0),new Date(0));retained.add(id);}let renders=0;const service=new VideoFrames({videoFile:async()=>f.source} as unknown as HostComputer,{} as Attachments,images,async()=>{renders++;return sheet;},()=>retained);await assert.rejects(service.inspect('bot','run',{path:f.source,reason:'inspect'},new AbortController().signal),/上限/);assert.equal(renders,0);assert.equal(readdirSync(images).length,128);retained.clear();await service.inspect('bot','run',{path:f.source,reason:'inspect'},new AbortController().signal);assert.equal(renders,1);assert.equal(readdirSync(images).filter(n=>n.endsWith('.png')).length,1);});

test('single-frame inspection can read detail while oversized sheets are rejected',()=>{assert.equal(videoFrameLayout(1).width,960);assert.equal(videoFrameLayout(1,1280).width,1280);assert.throws(()=>videoFrameRequest({count:24,frameWidth:1280}),/拼图过大/);});
