import test from 'node:test';import assert from 'node:assert/strict';import {startVncConnection,canvasHasFrame,type VncClient} from '../src/vnc-connection';
class Client extends EventTarget implements VncClient{background='';scaleViewport=false;resizeSession=true;viewOnly=true;closed=false;disconnect(){this.closed=true;this.dispatchEvent(new Event('disconnect'));}emit(name:string){this.dispatchEvent(new Event(name));}}
function setup(){let now=0,next=0,painted=false;const timers=new Map<number,{at:number;fn:()=>void}>(),clients:Client[]=[],states:string[]=[];const clock={later:(fn:()=>void,ms:number)=>{const id=++next;timers.set(id,{at:now+ms,fn});return id;},cancel:(id:unknown)=>{timers.delete(id as number);}};const advance=(ms:number)=>{const end=now+ms;for(;;){const entry=[...timers].sort((a,b)=>a[1].at-b[1].at)[0];if(!entry||entry[1].at>end)break;timers.delete(entry[0]);now=entry[1].at;entry[1].fn();}now=end;};const connection=startVncConnection({clock,create:()=>{const c=new Client();clients.push(c);return c;},hasFrame:()=>painted,onState:s=>states.push(s),control:false});return {connection,clients,states,advance,timers,paint:()=>{painted=true;}};}
test('slow first paint does not trigger the former 2.5-second reconnect',()=>{const f=setup();f.clients[0].emit('connect');f.advance(3000);assert.equal(f.clients.length,1);assert.equal(f.states.at(-1),'connecting');f.paint();f.advance(250);assert.equal(f.states.at(-1),'connected');f.connection.dispose();assert.equal(f.timers.size,0);});
test('cold disconnects reconnect automatically but stop after a bounded number of attempts',()=>{const f=setup();for(const delay of [500,1500,3000]){f.clients.at(-1)!.emit('disconnect');f.advance(delay);}assert.equal(f.clients.length,4);f.clients.at(-1)!.emit('disconnect');assert.equal(f.states.at(-1),'failed');f.advance(60000);assert.equal(f.clients.length,4);f.connection.dispose();});
test('handshake hangs are bounded, and disposal cancels pending retries and late events',()=>{const f=setup();f.advance(15000);assert.ok(f.clients[0].closed);f.connection.dispose();f.advance(60000);f.clients[0].emit('connect');assert.equal(f.clients.length,1);assert.equal(f.states.includes('connected'),false);assert.equal(f.timers.size,0);});
test('authentication failure is not retried; controls survive legitimate reconnects',()=>{const f=setup();f.clients[0].emit('securityfailure');f.advance(60000);assert.equal(f.clients.length,1);assert.equal(f.states.at(-1),'failed');f.connection.dispose();const g=setup();g.connection.setControl(true);assert.equal(g.clients[0].viewOnly,false);g.clients[0].emit('disconnect');g.advance(500);assert.equal(g.clients[1].viewOnly,false);g.connection.dispose();});
test('a black opaque framebuffer is valid, while an untouched transparent canvas is not',()=>{const canvas=(alpha:number)=>({width:100,height:100,getContext:()=>({getImageData:()=>({data:[0,0,0,alpha]})})}) as unknown as HTMLCanvasElement;assert.equal(canvasHasFrame(canvas(255)),true);assert.equal(canvasHasFrame(canvas(0)),false);assert.equal(canvasHasFrame(null),false);});
test('a flapping connection does not reset its retry budget on a single painted frame',()=>{const f=setup();f.paint();for(const delay of [500,1500,3000]){f.clients.at(-1)!.emit('connect');f.clients.at(-1)!.emit('disconnect');f.advance(delay);}f.clients.at(-1)!.emit('connect');f.clients.at(-1)!.emit('disconnect');assert.equal(f.states.at(-1),'failed');f.connection.dispose();});
