import test from 'node:test';
import assert from 'node:assert/strict';
import {createWerewolf,acceptAction,view} from '../electron/core/games/werewolf';
import {gamePrompt} from '../electron/core/games/model-player';
const players=Array.from({length:7},(_,i)=>({id:String(i),name:'玩家'+i,human:i===3,color:'#887799'}));
const make=()=>createWerewolf('seven',players,['wolf','wolf','seer','witch','villager','villager','villager']);
function wolfPlans(s:ReturnType<typeof make>){while(s.requests[0]?.kind==='wolf_plan')acceptAction(s,s.requests[0].id,{text:'今晚先统一刀口，白天一人起跳、一人看情况。'});}
function firstActions(s:ReturnType<typeof make>,victim='4'){wolfPlans(s);for(const r of [...s.requests])acceptAction(s,r.id,{target:r.kind==='kill'?victim:'0'});return s.requests[0];}
test('seven player deck has witch and stable varied personalities',()=>{for(let i=0;i<10;i++){const s=createWerewolf('seven',players);assert.equal(s.seats.filter(p=>p.role==='witch').length,1);assert.equal(s.seats.filter(p=>p.role==='wolf').length,2);assert.equal(new Set(s.seats.filter(p=>!p.human).map(p=>p.personality)).size,6);const r=s.requests[0];const prompt=JSON.parse(gamePrompt(view(s,r.seatId),r));assert.equal(prompt.context.personal.self.personality,s.seats.find(p=>p.id===r.seatId)?.personality);}});
test('wolf night chat reaches the teammate and stays hidden from good players',()=>{const s=make(),first=s.requests[0],wolves=s.seats.filter(p=>p.role==='wolf');assert.equal(first.kind,'wolf_plan');acceptAction(s,first.id,{text:'我提议刀5号，我来悍跳。'});const second=s.requests[0];assert.equal(second.kind,'wolf_plan');assert.notEqual(second.seatId,first.seatId);assert(view(s,second.seatId).logs.some(e=>e.text.includes('刀5号')));assert(!view(s,s.seats.find(p=>p.role==='villager')!.id).logs.some(e=>e.text.includes('刀5号')));assert.deepEqual(new Set(view(s,second.seatId).seats.filter(p=>p.role==='wolf').map(p=>p.id)),new Set(wolves.map(p=>p.id)));});
test('witch acts before deaths, saves once, and only witch sees victim',()=>{const s=make(),r=firstActions(s);assert.equal(r.kind,'witch');assert(s.seats.every(p=>p.alive));assert.equal(view(s,'3').pending[0].witch?.victim,'4');assert.equal(view(s,'4').pending.length,0);assert.equal(view(s,undefined,true).pending.length,0);acceptAction(s,r.id,{potion:'save'});assert(s.seats.every(p=>p.alive));assert.equal(s.potions?.save,false);assert.equal(s.phase,'speech');assert(!view(s,'4').logs.some(l=>l.text.includes('使用解药')));});
test('poison and wolf attack resolve together, even if witch is attacked',()=>{const s=make(),r=firstActions(s,'3');assert.equal(r.witch?.canSave,true);acceptAction(s,r.id,{potion:'poison',target:'0'});assert.equal(s.seats[3].alive,false);assert.equal(s.seats[0].alive,false);assert.equal(s.potions?.poison,false);assert.equal(s.potions?.save,true);assert.equal(s.status,'running');});
test('witch cannot self save after first night, use exhausted potion or poison self',()=>{const s=make();s.day=2;const r=firstActions(s,'3');assert.equal(r.witch?.canSave,false);assert.throws(()=>acceptAction(s,r.id,{potion:'save'}));assert.throws(()=>acceptAction(s,r.id,{potion:'poison',target:'3'}));acceptAction(s,r.id,{potion:'skip'});assert.equal(s.seats[3].alive,false);const exhausted=make();exhausted.potions={save:false,poison:false};const e=firstActions(exhausted);assert.equal(e.witch?.victim,undefined);assert.equal(e.witch?.canSave,false);assert.equal(e.witch?.canPoison,false);assert.throws(()=>acceptAction(exhausted,e.id,{potion:'save'}));assert.throws(()=>acceptAction(exhausted,e.id,{potion:'poison',target:'0'}));});
test('witch timeout skips potion without inventing save or poison',()=>{const s=make(),r=firstActions(s);acceptAction(s,r.id,{},true);assert.equal(s.seats[4].alive,false);assert.deepEqual(s.potions,{save:true,poison:true});assert(!view(s,'4').logs.some(e=>e.text.includes('玩家3 夜间行动超时')));});
test('seven player random legal games finish including potion decisions',()=>{for(let i=0;i<100;i++){const s=createWerewolf('seven',players);let steps=0;while(s.status==='running'&&steps++<500){const r=s.requests[0];assert(r);const action=r.kind==='wolf_plan'?{text:'先统一刀口，明天再按发言调整。'}:r.kind==='speak'?{text:'根据前面的发言，我更怀疑其中一位玩家。'}:r.kind==='witch'?r.witch?.canSave&&Math.random()<.5?{potion:'save' as const}:r.witch?.canPoison&&Math.random()<.5?{potion:'poison' as const,target:r.targets[0]}:{potion:'skip' as const}:{target:r.targets[Math.floor(Math.random()*r.targets.length)]};acceptAction(s,r.id,action);}assert.equal(s.status,'finished');assert(s.winner);}});
