import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {GameRuntime} from '../electron/core/games/runtime';
import {createWerewolf,acceptAction} from '../electron/core/games/werewolf';
const players=Array.from({length:7},(_,i)=>({id:String(i),name:'p'+i,human:false,color:'#887799'}));
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
test('fast parallel decisions must be saved without waiting for a stalled peer',async()=>{const dir=mkdtempSync(join(tmpdir(),'wolf-review-'));const s=createWerewolf('g',players,['wolf','wolf','seer','witch','villager','villager','villager']);while(s.requests[0]?.kind==='wolf_plan')acceptAction(s,s.requests[0].id,{text:'统一刀口。'});s.status='paused';writeFileSync(join(dir,'matches.json'),JSON.stringify([s]));const runtime=new GameRuntime(dir,async(p,_v,r,signal)=>{if(p.id==='1')return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('aborted')),{once:true}));return {target:r.targets[0]};});try{runtime.control(s.id,'resume');await delay(40);const disk=JSON.parse((await import('node:fs')).readFileSync(join(dir,'matches.json'),'utf8'))[0];assert.equal(disk.accepted.length,4);}finally{runtime.control(s.id,'stop');runtime.dispose();await delay(10);rmSync(dir,{recursive:true,force:true});}});
test('dispose must not relaunch AI requests from old worker finalizers',async()=>{const dir=mkdtempSync(join(tmpdir(),'wolf-review-'));let calls=0;const runtime=new GameRuntime(dir,async(_p,_v,r)=>{calls++;await delay(20);return {target:r.targets[0],text:'test'};});const s=runtime.create({groupId:'g',players});const before=calls;runtime.dispose();await delay(45);try{assert.equal(calls,before);}finally{runtime.dispose();await delay(30);rmSync(dir,{recursive:true,force:true});}});
test('duplicate player identities are rejected before assigning internal seat IDs',()=>{const dir=mkdtempSync(join(tmpdir(),'wolf-review-'));const runtime=new GameRuntime(dir,async()=>({}));try{assert.throws(()=>runtime.create({groupId:'g',players:players.map(p=>({...p,id:'same'}))}));}finally{const current=runtime.read('g');if(current)runtime.control(current.id,'stop');runtime.dispose();rmSync(dir,{recursive:true,force:true});}});
test('all abstaining in the first ballot must not be reported as a second tie',()=>{const s=createWerewolf('g',players);s.phase='vote';s.requests=players.map(p=>({id:'v'+p.id,seatId:p.id,kind:'vote',targets:players.filter(t=>t.id!==p.id).map(t=>t.id)}));for(const r of [...s.requests])acceptAction(s,r.id,{},true);assert(s.logs.some(e=>e.text.includes('全部弃权')));assert(!s.logs.some(e=>e.text.includes('再次平票')));});
test('trace connects model inputs, returns and committed actions without exposing other identities',async()=>{const dir=mkdtempSync(join(tmpdir(),'wolf-trace-'));const runtime=new GameRuntime(dir,async(_p,_v,r)=>r.kind==='wolf_plan'?{text:'先刀信息位，我来起跳。',note:'先协调狼队分工。'}:r.kind==='witch'?{potion:'skip',note:'暂时留药。'}:r.kind==='speak'?{text:'我先听具体矛盾。',note:'避免过早站边。'}:{target:r.targets[0],note:'选择当前目标。'});try{const s=runtime.create({groupId:'trace',players});for(let i=0;i<30&&runtime.inspect(s.id).filter(t=>t.type==='model_started').length<5;i++)await delay(50);runtime.control(s.id,'pause');const traces=runtime.inspect(s.id);const starts=traces.filter(t=>t.type==='model_started');assert(starts.length>=5);assert(starts.some(t=>t.kind==='wolf_plan'));for(const t of starts){const input=JSON.parse(t.input!);const self=input.context.personal.self;assert(self.role);assert.deepEqual(t.skills?.map(s=>s.id),['werewolf-player','werewolf-wolf','werewolf-seer','werewolf-witch','werewolf-villager','werewolf-playbook']);assert(t.instruction?.includes('已加载技能'));assert(input.context.shared.seats.every((p:any)=>!p.role));assert(input.context.personal.teammates.every((p:any)=>self.role==='wolf'&&p.role==='wolf'));assert.equal(self.source,'role_assignment');assert(traces.some(e=>e.type==='model_returned'&&e.requestId===t.requestId&&e.elapsedMs!==undefined));assert(traces.some(e=>e.type==='action_accepted'&&e.requestId===t.requestId));}assert(traces.some(t=>t.type==='request_created'&&t.kind==='witch'));assert(traces.some(t=>t.type==='model_returned'&&t.action?.note));assert.equal(new Set(traces.map(t=>t.seq)).size,traces.length);}finally{runtime.dispose();rmSync(dir,{recursive:true,force:true});}});
test('human game private traces are unavailable until game ends',()=>{const dir=mkdtempSync(join(tmpdir(),'wolf-trace-'));const runtime=new GameRuntime(dir,async()=>new Promise(()=>{}));try{const s=runtime.create({groupId:'trace',players:players.map((p,i)=>({...p,human:i===0}))});assert.throws(()=>runtime.inspect(s.id),/结束后/);assert(!('trace' in runtime.read('trace')!));runtime.control(s.id,'stop');assert(runtime.inspect(s.id).some(t=>t.type==='stop'));}finally{runtime.dispose();rmSync(dir,{recursive:true,force:true});}});
test('invalid model action records returned value, rejection reason and retry before pausing',async()=>{const dir=mkdtempSync(join(tmpdir(),'wolf-trace-'));const runtime=new GameRuntime(dir,async()=>({target:'invalid'}));try{const s=runtime.create({groupId:'trace',players});await delay(40);const trace=runtime.inspect(s.id);assert.equal(runtime.read('trace')?.status,'paused');assert.equal(trace.filter(t=>t.type==='model_failed').length,2);assert(trace.some(t=>t.type==='model_failed'&&t.kind==='wolf_plan'&&t.attempt===2&&t.detail?.includes('非法行动')));assert(trace.some(t=>t.type==='model_returned'&&t.action?.target==='invalid'));assert(trace.some(t=>t.type==='failure_pause'));assert(!trace.some(t=>t.type==='action_accepted'));}finally{runtime.dispose();rmSync(dir,{recursive:true,force:true});}});
test('AI response expiry pauses without choosing no and resume only retries unfinished seats',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'wolf-timeout-'));
 const roster=Array.from({length:12},(_,i)=>({...players[0],id:String(i),name:'p'+i}));
 const s=createWerewolf('timeout',roster,undefined,'standard12');s.status='paused';s.phase='election';s.twelve!.stage='上警报名';s.requests=roster.map(p=>({id:'join-'+p.id,seatId:p.id,kind:'sheriff_join',targets:[],remainingMs:1}));s.answers={};
 writeFileSync(join(dir,'matches.json'),JSON.stringify([s]));let retry=false;const calls:string[]=[];
 const runtime=new GameRuntime(dir,async(p,_v,r,signal)=>{calls.push(p.id+':'+r.kind);if(r.kind==='sheriff_join'&&(p.id!=='11'||retry))return {choice:true};return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('aborted')),{once:true}));},()=>{},{aiTimeoutMs:80});
 try{
 runtime.control(s.id,'resume');await delay(330);
 assert.equal(runtime.read('timeout')?.status,'paused');assert.match(runtime.read('timeout')!.error!,/模型响应超时/);
 let disk=JSON.parse((await import('node:fs')).readFileSync(join(dir,'matches.json'),'utf8'))[0];
 assert.equal(disk.requests.length,1);assert.equal(disk.requests[0].id,'join-11');assert.equal(Object.keys(disk.answers).length,11);assert(!disk.accepted.includes('join-11'));assert(!disk.logs.some((l:any)=>l.text.includes('报名超时，按规则')));
 retry=true;runtime.control(s.id,'resume');await delay(25);
 disk=JSON.parse((await import('node:fs')).readFileSync(join(dir,'matches.json'),'utf8'))[0];assert.equal(disk.twelve.applicants.length,12);assert.equal(calls.filter(x=>x==='0:sheriff_join').length,1);assert.equal(calls.filter(x=>x==='11:sheriff_join').length,2);
 }finally{runtime.dispose();await delay(10);rmSync(dir,{recursive:true,force:true});}
});
test('human timers still freeze on pause and expire using game rules',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'wolf-human-time-'));const roster=Array.from({length:12},(_,i)=>({...players[0],id:String(i),name:'p'+i,human:i===0}));const s=createWerewolf('human-timer',roster,undefined,'standard12');s.phase='election';s.status='paused';s.twelve!.stage='上警报名';s.requests=[{id:'human-join',seatId:'0',kind:'sheriff_join',targets:[],remainingMs:100}];s.answers={};writeFileSync(join(dir,'matches.json'),JSON.stringify([s]));const runtime=new GameRuntime(dir,async()=>new Promise(()=>{}));try{runtime.control(s.id,'resume');const paused=runtime.control(s.id,'pause');assert(paused.clock?.remainingMs!>0);await delay(150);assert.equal(runtime.read('human-timer')?.phase,'election');runtime.control(s.id,'resume');await delay(550);const disk=JSON.parse((await import('node:fs')).readFileSync(join(dir,'matches.json'),'utf8'))[0];assert(disk.accepted.includes('human-join'));assert(disk.trace.some((t:any)=>t.type==='timeout'&&t.seatId==='0'));}finally{runtime.dispose();rmSync(dir,{recursive:true,force:true});}
});
