import {createHash} from 'node:crypto';
import {readFileSync,realpathSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {join,relative,isAbsolute} from 'node:path';
import type {DesignSystemCatalog,DesignSystemDetail,DesignSystemManifest} from '../../src/designer-types';
export class DesignSystems {
 readonly catalog:DesignSystemCatalog;
 private summaries?:ReturnType<DesignSystems["describe"]>;
 private describe(){return this.catalog.systems.map(({files,...summary})=>{let description=summary.description;try{const source=this.read(summary.id,"DESIGN.md").toString("utf8");const paragraphs=source.split(/\r?\n\s*\r?\n/).map(p=>p.trim()).filter(p=>p&&!/^(#|>|[-*] |```|\|)/.test(p));const text=paragraphs[0]?.replace(/\[([^\]]+)\]\([^)]*\)/g,"$1").replace(/[*`_]/g,"").replace(/\s+/g," ");if(text)description=text.length>260?text.slice(0,257).replace(/\s+\S*$/,"")+"…":text;}catch{}return {...summary,description};});}
 constructor(readonly root:string,readonly archiveRoot?:string){this.catalog=JSON.parse(readFileSync(join(root,'catalog.json'),'utf8'));if(this.catalog.version!==1||!Array.isArray(this.catalog.systems)||!this.catalog.systems.length)throw Error('设计系统资源清单无效');}
 list(){return this.summaries??=this.describe();}
 get(id:string,version?:string):DesignSystemManifest{const system=this.catalog.systems.find(s=>s.id===id);if(system&&(!version||system.version===version))return system;if(this.archiveRoot&&version&&/^[a-f0-9]{40}$/.test(version)&&/^[a-z0-9-]+$/.test(id)){const file=join(this.archiveRoot,version,id,'pinned-manifest.json');if(existsSync(file)){const pinned=JSON.parse(readFileSync(file,'utf8'));if(pinned.id===id&&pinned.version===version)return pinned;}}throw Error('所选设计系统版本不在本地资源库中');}
 read(id:string,path:string,version?:string){const system=this.get(id,version),file=system.files.find(f=>f.path===path);if(!file)throw Error('文件不在设计系统资源清单中');const base=this.catalog.systems.some(s=>s.id===id&&s.version===system.version)?this.root:join(this.archiveRoot!,system.version);const root=realpathSync(join(base,id)),target=realpathSync(join(root,path)),rel=relative(root,target);if(isAbsolute(rel)||rel==='..'||rel.startsWith('..'+String.fromCharCode(92))||rel.startsWith('../'))throw Error('设计资源路径越界');const bytes=readFileSync(target);if(bytes.length!==file.bytes||createHash('sha256').update(bytes).digest('hex')!==file.sha256)throw Error('设计系统资源已变化，请修复应用安装');return bytes;}
 pin(id:string,version?:string){const system=this.get(id,version);if(!this.archiveRoot)return system;const target=join(this.archiveRoot,system.version,id);if(existsSync(join(target,'pinned-manifest.json')))return system;for(const file of system.files){const bytes=this.read(id,file.path,system.version),path=join(target,file.path);mkdirSync(join(path,'..'),{recursive:true});writeFileSync(path,bytes);}writeFileSync(join(target,'pinned-manifest.json'),JSON.stringify(system));return system;}
 detail(id:string):DesignSystemDetail{const {files,...summary}=this.get(id);const read=(path:string)=>files.some(f=>f.path===path)?this.read(id,path).toString('utf8'):'';return {...summary,design:read('DESIGN.md'),tokens:read('tokens.css'),components:read('components.html')};}
 context(id:string,version?:string){const system=this.get(id,version);const text=(path:string,max:number,css=false)=>{const raw=system.files.some(f=>f.path===path)?this.read(id,path,version).toString('utf8'):'';const content=css?raw.replace(/\/\*[\s\S]*?\*\//g,'').trim():raw;return {content:content.slice(0,max),truncated:content.length>max};};const design=text('DESIGN.md',24000),tokens=text('tokens.css',12000,true),components=text('components.manifest.json',3500);return {id,version:system.version,source:system.source,license:system.license,design:design.content,tokens:tokens.content,components:components.content,referenceTruncated:{design:design.truncated,tokens:tokens.truncated,components:components.truncated},files:system.files.map(f=>f.path)};}
}
