import type { LayaFeature } from '../core/model/laya-feature';
import type { BrowserWindow } from 'electron';
import type { IpcHandler, IpcMethod } from '../../shared/ipc';
import type { StateBase } from '../../shared/state-sync';
import type { BotGreetings } from '../core/agent/bot-greetings';
import type { BotRuntime } from '../core/agent/bot-runtime';
import type { ChatPinQueue } from '../core/agent/chat-pins';
import type { Harness } from '../core/agent/harness';
import type { Interactions } from '../core/agent/interactions';
import type { AppUpdates } from '../core/app/app-updates';
import type { Diagnostics } from '../core/app/diagnostics';
import type { ArtifactService } from '../core/attachments/artifacts';
import type { Attachments } from '../core/attachments/attachments';
import type { DesignFonts } from '../core/designer/design-fonts';
import type { DesignStore } from '../core/designer/design-store';
import type { DesignSystems } from '../core/designer/design-systems';
import type { DesignerFiles } from '../core/designer/designer-files';
import type { Integrations } from '../core/extensions/integrations';
import type { GameRuntime } from '../core/games/runtime';
import type { PersonaService } from '../core/persona/persona-service';
import type { GroupChats } from '../core/group/group-chats';
import type { CommandPermissions } from '../core/host/command-permissions';
import type { HostComputer } from '../core/host/host';
import type { HostApprovals } from '../core/host/host-approvals';
import type { Cognition } from '../core/memory/cognition';
import type { ModelClient } from '../core/model/model';
import type { ModelProviders } from '../core/model/model-providers';
import type { PeerChats } from '../core/peer/peer-chats';
import type { AgentPreviews } from '../core/preview/agent-previews';
import type { TaskScheduler } from '../core/scheduler/task-scheduler';
import type { Store } from '../core/storage/store';
import type { ComputerController } from '../core/vm/computer';
import type { VmController } from '../core/vm/vm';
import type { WebPreviewBrowser } from '../windows/web-preview';

type IpcHandle = <M extends IpcMethod>(method: M, callback: IpcHandler<M>) => void;

// Handlers read services through this object on every call, so main.ts implements the fields as getters over
// its live variables: some services are optional or replaced after registration.
export interface IpcContext {
  readonly handle: IpcHandle;
  readonly window: BrowserWindow | undefined;
  readonly dataDir: string;
  readonly store: Store;
  readonly vm: VmController;
  readonly computer: ComputerController;
  readonly harness: BotRuntime;
  readonly generalHarness: Harness;
  readonly model: ModelClient;
  readonly providers: ModelProviders;
  readonly artifacts: ArtifactService;
  readonly attachments: Attachments;
  readonly integrations: Integrations;
  readonly interactions: Interactions;
  readonly host: HostComputer;
  readonly commandPermissions: CommandPermissions;
  readonly hostApprovals: HostApprovals;
  readonly cognition: Cognition;
  readonly designSystems: DesignSystems;
  readonly designStore: DesignStore;
  readonly designerFiles: DesignerFiles;
  readonly designFonts: DesignFonts;
  readonly peerChats: PeerChats | undefined;
  readonly groupChats: GroupChats | undefined;
  readonly games: GameRuntime | undefined;
  readonly persona: PersonaService | undefined;
  readonly layaFeature: LayaFeature | undefined;
  readonly chatPins: ChatPinQueue | undefined;
  readonly scheduler: TaskScheduler | undefined;
  readonly greetings: BotGreetings | undefined;
  readonly webPreview: WebPreviewBrowser | undefined;
  readonly appUpdates: AppUpdates | undefined;
  readonly diagnostics: Diagnostics | undefined;
  readonly agentPreviews: AgentPreviews | undefined;
  readonly updatePreparing: boolean;
  previewDirty: boolean;
  previewWrites: number;
  appearanceDimmed: boolean;
  readState(): StateBase;
  changed(): void;
  beforeModelChange(botIds: string[]): void;
  afterModelChange(): void;
  saveAppearance(value: unknown): void;
}
