import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import type {AnnotationTool,PreviewAnnotation,PreviewMode} from './preview-editor-types';
export function FileAnnotationLayer({itemId,revision,mode,tool,onChange,register,initialCache,onCacheChange}:{initialCache?:Record<string,PreviewAnnotation[]>;onCacheChange?:(value:Record<string,PreviewAnnotation[]>)=>void;itemId:string;revision:string;mode:PreviewMode;tool:AnnotationTool;onChange:(value:PreviewAnnotation[])=>void;register:(update:(value:PreviewAnnotation[])=>void)=>()=>void}){
 const root=useRef<SVGSVGElement>(null),targets=useRef({x:0,y:0,width:1,height:1,key:''}),cache=useRef(new Map<string,PreviewAnnotation[]>(Object.entries(initialCache||{}).filter(([key])=>!key.startsWith('web:')))),[marks,setMarks]=useState<PreviewAnnotation[]>([]),[shape,setShape]=useState<PreviewAnnotation>(),[geometry,setGeometry]=useState({x:0,y:0,width:1,height:1,hostWidth:1,hostHeight:1,enabled:false}),drawing=useRef<PreviewAnnotation|undefined>(undefined),latestShape=useRef<PreviewAnnotation|undefined>(undefined);
 const update=(value:PreviewAnnotation[])=>{cache.current.set(targets.current.key,value);setMarks(value);onCacheChange?.(Object.fromEntries(cache.current));};
 useEffect(()=>register(update),[register]);useEffect(()=>onChange(marks),[marks,onChange]);
 useLayoutEffect(()=>{const svg=root.current,content=svg?.closest<HTMLElement>('.fp-content');if(!svg||!content)return;let frame=0;let observed:Element|undefined;
  const refresh=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(content.querySelector('.web-preview')){setGeometry(old=>old.enabled?{...old,enabled:false}:old);return;}const target=content.querySelector<HTMLElement>('.fp-pdf-viewport .fp-pdf-page,.fp-image-space img,.fp-code-text code,.fp-paper,.fp-csv,.cm-content');if(!target){setGeometry(old=>old.enabled?{...old,enabled:false}:old);return;}
   if(observed!==target){if(observed)resize.unobserve(observed);resize.observe(target);observed=target;}
   const a=target.getBoundingClientRect(),b=content.getBoundingClientRect(),page=content.querySelector<HTMLElement>('[data-preview-page]')?.dataset.previewPage||'1',key=itemId+':'+revision+':'+page+':'+(target.matches('.cm-content')?'editor':'preview');
   if(targets.current.key!==key){targets.current.key=key;setMarks(cache.current.get(key)||[]);setShape(undefined);drawing.current=undefined;}
   targets.current={x:a.x,y:a.y,width:Math.max(1,a.width),height:Math.max(1,a.height),key};setGeometry({x:a.x-b.x,y:a.y-b.y,width:a.width,height:a.height,hostWidth:b.width,hostHeight:b.height,enabled:a.width>0&&a.height>0});
  });};const resize=new ResizeObserver(refresh);resize.observe(content);const mutations=new MutationObserver(refresh);mutations.observe(content,{childList:true,subtree:true,attributes:true,attributeFilter:['data-preview-page']});content.addEventListener('scroll',refresh,true);window.addEventListener('resize',refresh);refresh();return()=>{resize.disconnect();mutations.disconnect();content.removeEventListener('scroll',refresh,true);window.removeEventListener('resize',refresh);cancelAnimationFrame(frame);};
 },[itemId,revision]);
 const point=(e:React.PointerEvent)=>({x:Math.max(0,Math.min(1,(e.clientX-targets.current.x)/targets.current.width)),y:Math.max(0,Math.min(1,(e.clientY-targets.current.y)/targets.current.height))});
 const coordinate=(p:{x:number;y:number})=>({x:geometry.x+p.x*geometry.width,y:geometry.y+p.y*geometry.height});
 const render=(a:PreviewAnnotation,i:number)=>{const p=coordinate(a),end=a.end&&coordinate(a.end),x=p.x,y=p.y,w=(a.w||0)*geometry.width,h=(a.h||0)*geometry.height;return <g key={a.id}>{(a.type==='rect'||a.type==='element')&&<rect x={x} y={y} width={w} height={h} fill={a.color+'0b'} stroke={a.color} strokeWidth={2}/>} {a.type==='arrow'&&end&&<><line x1={x} y1={y} x2={end.x} y2={end.y} stroke={a.color} strokeWidth={2}/><path d={`M ${end.x-10*Math.cos(Math.atan2(end.y-y,end.x-x)-.45)} ${end.y-10*Math.sin(Math.atan2(end.y-y,end.x-x)-.45)} L ${end.x} ${end.y} L ${end.x-10*Math.cos(Math.atan2(end.y-y,end.x-x)+.45)} ${end.y-10*Math.sin(Math.atan2(end.y-y,end.x-x)+.45)}`} fill="none" stroke={a.color} strokeWidth={2}/></>}{a.type==='pen'&&<polyline points={a.points?.map(coordinate).map(p=>p.x+','+p.y).join(' ')} fill="none" stroke={a.color} strokeWidth={3} strokeLinecap="round" strokeLinejoin="round"/>}{a.type==='text'&&<><rect x={x} y={y} width={Math.max(65,(a.text||'标注').length*14+16)} height={28} fill="#fff" rx={4}/><text x={x+8} y={y+20} fontSize={14} fill={a.color}>{a.text||'标注'}</text></>}{i>=0&&<><circle cx={x+9} cy={y+9} r={9} fill={a.color}/><text x={x+9} y={y+13} textAnchor="middle" fontSize={11} fill="#fff">{i+1}</text></>}</g>;};
 return <svg ref={root} className="file-annotation-layer" style={{display:geometry.enabled?undefined:'none',pointerEvents:mode==='annotate'?'auto':'none',visibility:mode==='edit'?'hidden':undefined}} viewBox={`0 0 ${geometry.hostWidth} ${geometry.hostHeight}`} aria-label="文件标注" onPointerDown={e=>{if(e.button!==0||mode!=='annotate'||marks.length>=100)return;const p=point(e),a:PreviewAnnotation={id:crypto.randomUUID(),type:tool==='element'?'rect':tool,...p,w:0,h:0,color:'#3975c6',...(tool==='pen'?{points:[p]}:{}),...(tool==='text'?{text:'标注'}:{})};drawing.current=a;latestShape.current=a;setShape(a);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const a=drawing.current;if(!a)return;const p=point(e);const next={...a,...(a.type==='rect'?{x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),w:Math.abs(p.x-a.x),h:Math.abs(p.y-a.y)}:a.type==='arrow'?{end:p}:a.type==='pen'?{points:(a.points!.length<3000?(a.points!.push(p),a.points):a.points)}:{})};latestShape.current=next;setShape(next);}} onPointerUp={()=>{const a=latestShape.current;if(a&&(a.type==='text'||(a.w||0)>.002&&(a.h||0)>.002||a.end||a.points&&a.points.length>2))update([...marks,a]);drawing.current=undefined;latestShape.current=undefined;setShape(undefined);}} onPointerCancel={()=>{drawing.current=undefined;setShape(undefined);}}>{marks.map(render)}{shape&&render(shape,-1)}</svg>;
}
