import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import type {AnnotationTool,PreviewAnnotation,PreviewMode} from './preview-editor-types';
export function FileAnnotationLayer({itemId,revision,mode,tool,onChange,register,initialCache,onCacheChange,selectedAnnotationId,onSelectAnnotation}:{selectedAnnotationId?:string;onSelectAnnotation?:(id:string)=>void;initialCache?:Record<string,PreviewAnnotation[]>;onCacheChange?:(value:Record<string,PreviewAnnotation[]>)=>void;itemId:string;revision:string;mode:PreviewMode;tool:AnnotationTool;onChange:(value:PreviewAnnotation[])=>void;register:(update:(value:PreviewAnnotation[])=>void)=>()=>void}){
 const root=useRef<SVGSVGElement>(null),targets=useRef({x:0,y:0,width:1,height:1,key:''}),cache=useRef(new Map<string,PreviewAnnotation[]>(Object.entries(initialCache||{}).filter(([key])=>!key.startsWith('web:')))),[marks,setMarks]=useState<PreviewAnnotation[]>([]),[shape,setShape]=useState<PreviewAnnotation>(),[geometry,setGeometry]=useState({x:0,y:0,width:1,height:1,hostWidth:1,hostHeight:1,enabled:false}),drawing=useRef<PreviewAnnotation|undefined>(undefined),latestShape=useRef<PreviewAnnotation|undefined>(undefined),pointer=useRef<number|undefined>(undefined);
 const update=(value:PreviewAnnotation[])=>{cache.current.set(targets.current.key,value);setMarks(value);onCacheChange?.(Object.fromEntries(cache.current));};
 useEffect(()=>register(update),[register]);useEffect(()=>onChange(marks),[marks,onChange]);
 useLayoutEffect(()=>{const svg=root.current,content=svg?.closest<HTMLElement>('.fp-content');if(!svg||!content)return;let frame=0;let observed:Element|undefined;
  const refresh=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(content.querySelector('.web-preview')){setGeometry(old=>old.enabled?{...old,enabled:false}:old);return;}const target=content.querySelector<HTMLElement>('.fp-pdf-viewport .fp-pdf-page,.fp-image-space img,.fp-code-text code,.fp-paper,.fp-csv,.cm-content');if(!target){setGeometry(old=>old.enabled?{...old,enabled:false}:old);return;}
   if(observed!==target){if(observed)resize.unobserve(observed);resize.observe(target);observed=target;}
   const a=target.getBoundingClientRect(),b=content.getBoundingClientRect(),page=content.querySelector<HTMLElement>('[data-preview-page]')?.dataset.previewPage||'1',key=itemId+':'+revision+':'+page+':'+(target.matches('.cm-content')?'editor':'preview');
   if(targets.current.key!==key){targets.current.key=key;setMarks(cache.current.get(key)||[]);setShape(undefined);drawing.current=undefined;}
   targets.current={x:a.x,y:a.y,width:Math.max(1,a.width),height:Math.max(1,a.height),key};setGeometry({x:a.x-b.x,y:a.y-b.y,width:a.width,height:a.height,hostWidth:b.width,hostHeight:b.height,enabled:a.width>0&&a.height>0});
  });};const resize=new ResizeObserver(refresh);resize.observe(content);const mutations=new MutationObserver(refresh);mutations.observe(content,{childList:true,subtree:true,attributes:true,attributeFilter:['data-preview-page']});content.addEventListener('scroll',refresh,true);window.addEventListener('resize',refresh);refresh();return()=>{resize.disconnect();mutations.disconnect();content.removeEventListener('scroll',refresh,true);window.removeEventListener('resize',refresh);cancelAnimationFrame(frame);};
 },[itemId,revision]);
 useEffect(()=>{if(mode==='annotate')return;const id=pointer.current;if(id!==undefined&&root.current?.hasPointerCapture(id))root.current.releasePointerCapture(id);pointer.current=undefined;drawing.current=undefined;latestShape.current=undefined;setShape(undefined);},[mode]);
 const point=(e:React.PointerEvent)=>({x:Math.max(0,Math.min(1,(e.clientX-targets.current.x)/targets.current.width)),y:Math.max(0,Math.min(1,(e.clientY-targets.current.y)/targets.current.height))});
 const coordinate=(p:{x:number;y:number})=>({x:geometry.x+p.x*geometry.width,y:geometry.y+p.y*geometry.height});
 const render=(a:PreviewAnnotation,i:number)=>{const p=coordinate(a),end=a.end&&coordinate(a.end),x=p.x,y=p.y,w=(a.w||0)*geometry.width,h=(a.h||0)*geometry.height;return <g key={a.id} style={{pointerEvents:mode==='browse'?'visiblePainted':'none',cursor:'pointer'}} onPointerDown={event=>{if(mode==='browse'){event.stopPropagation();onSelectAnnotation?.(a.id);}}}>{(a.type==='rect'||a.type==='element')&&<rect x={x} y={y} width={w} height={h} fill={a.color+'0b'} stroke={a.color} strokeWidth={selectedAnnotationId===a.id?3:2}/>} {a.type==='arrow'&&end&&<><line x1={x} y1={y} x2={end.x} y2={end.y} stroke={a.color} strokeWidth={2}/><path d={`M ${end.x-10*Math.cos(Math.atan2(end.y-y,end.x-x)-.45)} ${end.y-10*Math.sin(Math.atan2(end.y-y,end.x-x)-.45)} L ${end.x} ${end.y} L ${end.x-10*Math.cos(Math.atan2(end.y-y,end.x-x)+.45)} ${end.y-10*Math.sin(Math.atan2(end.y-y,end.x-x)+.45)}`} fill="none" stroke={a.color} strokeWidth={2}/></>}{a.type==='pen'&&<polyline points={a.points?.map(coordinate).map(p=>p.x+','+p.y).join(' ')} fill="none" stroke={a.color} strokeWidth={3} strokeLinecap="round" strokeLinejoin="round"/>}{a.type==='text'&&<><rect x={x} y={y} width={Math.max(65,(a.text||'标注').length*14+16)} height={28} fill="#fff" rx={4}/><text x={x+8} y={y+20} fontSize={14} fill={a.color}>{a.text||'标注'}</text></>}{i>=0&&<><circle cx={x+9} cy={y+9} r={9} fill={a.color}/><text x={x+9} y={y+13} textAnchor="middle" fontSize={11} fill="#fff">{i+1}</text></>}</g>;};
 const move=(p:{x:number;y:number})=>{const a=drawing.current;if(!a)return;const last=latestShape.current||a;const next={...a,...(a.type==='rect'?{x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),w:Math.abs(p.x-a.x),h:Math.abs(p.y-a.y)}:a.type==='arrow'?{end:p}:a.type==='pen'?{points:[...(last.points||[]).slice(-2998),p]}:{})};latestShape.current=next;setShape(next);return next;};
 useEffect(()=>{const svg=root.current;if(!svg)return;const wheel=(event:WheelEvent)=>{const content=svg.closest('.fp-content'),view=content?.querySelector<HTMLElement>('.fp-pdf-viewport,.fp-image-stage,.cm-scroller,.fp-csv,.fp-document-stage');if(!view)return;event.preventDefault();const factor=event.deltaMode===1?16:event.deltaMode===2?view.clientHeight:1;view.scrollBy(event.deltaX*factor,event.deltaY*factor);};svg.addEventListener('wheel',wheel,{passive:false});return()=>svg.removeEventListener('wheel',wheel);},[]);
 return <svg ref={root} className="file-annotation-layer" style={{display:geometry.enabled?undefined:'none',pointerEvents:mode==='annotate'?'auto':'none',visibility:mode==='edit'?'hidden':undefined}} viewBox={`0 0 ${geometry.hostWidth} ${geometry.hostHeight}`} aria-label="文件标注" onPointerDown={e=>{
  if(e.button!==0||mode!=='annotate'||marks.length>=100||pointer.current!==undefined)return;
  const target=targets.current;if(e.clientX<target.x||e.clientX>target.x+target.width||e.clientY<target.y||e.clientY>target.y+target.height)return;
  const p=point(e),page=Number(root.current?.closest('.fp-content')?.querySelector<HTMLElement>('[data-preview-page]')?.dataset.previewPage)||undefined;
  const a:PreviewAnnotation={id:crypto.randomUUID(),type:tool==='element'?'rect':tool,...p,w:0,h:0,color:'#3975c6',...(page?{page}:{}),...(tool==='pen'?{points:[p]}:{})};
  pointer.current=e.pointerId;drawing.current=a;latestShape.current=a;setShape(a);e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();
 }} onPointerMove={e=>{if(pointer.current===e.pointerId)move(point(e));}} onPointerUp={e=>{
  if(pointer.current!==e.pointerId)return;const a=move(point(e));
  if(a&&(a.type==='text'||a.type==='pen'&&(a.points?.length||0)>2||a.type==='rect'&&(a.w||0)*targets.current.width>=3&&(a.h||0)*targets.current.height>=3||a.type==='arrow'&&a.end&&Math.hypot((a.end.x-a.x)*targets.current.width,(a.end.y-a.y)*targets.current.height)>=3))update([...marks,a]);
  pointer.current=undefined;drawing.current=undefined;latestShape.current=undefined;setShape(undefined);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);
 }} onPointerCancel={()=>{pointer.current=undefined;drawing.current=undefined;latestShape.current=undefined;setShape(undefined);}}>{marks.map(render)}{shape&&render(shape,-1)}</svg>;
}
