import {ROLE_NAMES,PHASE_NAMES,ACTION_NAMES} from './game-boards';
import {useEffect,useState} from 'react';
import type {GameTrace,GameView,GameAction} from './game-types';
const labels:Record<GameTrace['type'],string>={created:'创建对局',model_response:'接口返回',model_queued:'等待请求名额',request_created:'等待行动',model_started:'开始决策',model_returned:'完成决策',model_failed:'请求失败',model_cancelled:'请求取消',reply_discarded:'回答已过期',action_accepted:'行动生效',action_rejected:'行动被拒绝',timeout:'行动超时',transition:'阶段推进',pause:'暂停',resume:'继续',stop:'结束对局',recovered:'重启恢复',failure_pause:'异常暂停'};
const phases:Record<string,string>=PHASE_NAMES;
const kinds:Record<string,string>=ACTION_NAMES;
const roles:Record<string,string>=ROLE_NAMES;
export function GameDiagnostics({game}:{game:GameView}){
 const [events,setEvents]=useState<GameTrace[]>([]),[error,setError]=useState(''),[seat,setSeat]=useState(''),[mode,setMode]=useState<'decisions'|'technical'>('decisions');
 const allowed=!game.humanId||game.status==='finished';
 const name=(id?:string)=>{const i=game.seats.findIndex(p=>p.id===id);return i<0?'无':`${i+1} 号 ${game.seats[i].name}`;};
 const actionText=(a:GameAction,kind?:string)=>a.choice!==undefined?(kind==='withdraw'?(a.choice?'退水':'继续竞选'):(a.choice?'上警':'不上警')):a.direction?(a.direction==='clockwise'?'顺时针发言':'逆时针发言'):a.skip?(kind==='badge'?'撕毁警徽':kind==='guard'?'空守':kind==='shoot'?'放弃开枪':'弃票'):a.potion==='skip'?'本晚不用药':a.potion==='save'?'使用解药救人':a.potion==='poison'?`对 ${name(a.target)} 使用毒药`:kind==='wolf_plan'?a.text||'未提出计划':a.text||`${kinds[kind||'']||'选择'} ${name(a.target)}`;
 useEffect(()=>{if(!allowed)return;let live=true,pending=false;const read=async()=>{if(pending)return;pending=true;try{const next=await window.aelion.games.inspect({id:game.id});if(live){setEvents(next);setError('');}}catch(e){if(live)setError((e as Error).message);}finally{pending=false;}};void read();const timer=setInterval(()=>void read(),1500);return()=>{live=false;clearInterval(timer);};},[game.id,allowed]);
 const returned=events.filter(e=>e.type==='model_returned');
 function inputView(e:GameTrace){try{const data=JSON.parse(e.input!);const shared=data.context.shared,personal=data.context.personal;
 const renderLogs=(logs:any[])=><>{logs.map((l:any)=><p key={l.id}>{l.seatId?name(l.seatId)+'：':''}{l.text}</p>)}</>;
 return <>{e.skills&&<p><b>已读攻略：</b>{e.skills.map(s=>s.title).join('、')}</p>}<p><b>扮演玩家：</b>{name(data.you)}</p>
 {shared&&personal?<><details><summary>共享上下文 · 全员可见</summary><p>第 {shared.day} 天 · {phases[shared.phase]}；玩家座位与存活状态。这里不包含真实身份、性格预设或私有查验。</p>{renderLogs(shared.logs)}</details><details><summary>个人上下文 · 仅该玩家可见</summary><p><b>本人身份：</b>{roles[personal.self.role]} · 来源：开局分配</p><p><b>本局性格：</b>{personal.self.mbti||'未记录'} · 来源：本局生效配置</p>{personal.self.behaviorPolicy&&<p><b>行为策略：</b>{Object.values(personal.self.behaviorPolicy).join('；')}</p>}{personal.teammates.length>0&&<p><b>狼队友：</b>{personal.teammates.map((p:any)=>name(p.id)).join('、')} · 来源：狼人相互知晓身份规则，写入本人的私有上下文，非共享信息</p>}<p><b>私有事件：</b>由规则按可见权限投递，例如本人的查验、用药结果或狼队行动。</p>{personal.logs.length?renderLogs(personal.logs):<p>暂无私有事件。</p>}</details></>:<><p>旧记录未标注上下文来源，不能作为当时来源分类的证据。</p><p><b>已知身份：</b>{data.context.seats.filter((p:any)=>p.role).map((p:any)=>`${name(p.id)}：${roles[p.role]}`).join('；')}</p><details><summary>当时可见事件（来源未标注）</summary>{renderLogs(data.context.logs)}</details></>}
 <p><b>本次任务：</b>{kinds[data.request.kind]}{data.request.targets?.length?'；可选 '+data.request.targets.map(name).join('、'):''}{data.request.source==='private_action_request'?' · 来源：规则引擎发给本人的行动请求':''}</p>{data.request.witch&&<p>解药：{data.request.witch.canSave?'可使用':'不可使用'}；毒药：{data.request.witch.canPoison?'可使用':'已耗尽'}；可见被袭击者：{name(data.request.witch.victim)} · 女巫能力授权，仅本人可见</p>}<details><summary>规则与实际加载的攻略</summary><p>{e.instruction}</p></details></>;}catch{return <p>旧记录无法解析。</p>;}}
 function personalityView(e:GameTrace){
  if(e.type!=='model_returned'||!e.action)return null;
  const started=events.filter(t=>t.type==='model_started'&&t.requestId===e.requestId&&t.seq<e.seq).at(-1);
  let self:{mbti?:string;behaviorPolicy?:Record<string,string>}|undefined;
  try{self=JSON.parse(started?.input||'{}').context?.personal?.self;}catch{}
  const dimensions:Record<string,string>={interaction:'交流方式',evidence:'关注信息',evaluation:'判断偏好',commitment:'调整决定',risk:'本局风格'};
  const tags:Record<string,string>={E:'主动交流',I:'先观察',S:'关注事实',N:'关注关联',T:'侧重逻辑',F:'关注信任',J:'倾向定计划',P:'保留选择'};
  return <section className="wg-personality-decision"><div className="wg-personality-heading"><strong>{self?.mbti||'性格未记录'}</strong>{self?.mbti&&<span>{self.mbti.split('').map(c=>tags[c]).filter(Boolean).join(' · ')}</span>}</div><p className="wg-decision-action">{actionText(e.action,e.kind)}</p>{e.action.note&&<div className="wg-decision-reason"><b>判断依据</b><p>{e.action.note}</p></div>}{e.action.personalityNote?<div className="wg-decision-reason"><b>性格影响 <small>AI 自述</small></b><p>{e.action.personalityNote}</p></div>:null}{self?.behaviorPolicy&&<details className="wg-personality-details"><summary>查看本局性格倾向</summary><dl>{Object.entries(self.behaviorPolicy).map(([key,value])=><div key={key}><dt>{dimensions[key]||key}</dt><dd>{value}</dd></div>)}</dl></details>}</section>;

 }
 function detail(e:GameTrace){if(e.type==='created')return `${game.seats.length} 位玩家加入对局；${e.detail||''}`;if(e.type==='transition')return '当前进入'+phases[e.phase];if(e.type==='request_created')return '';return e.detail;}
 return <section className="wg-diagnostics" aria-label="运行记录"><div className="gg-config-heading"><strong>运行记录</strong>{allowed&&<select aria-label="筛选玩家记录" value={seat} onChange={e=>setSeat(e.target.value)}><option value="">全部玩家</option>{game.seats.map(p=><option key={p.id} value={p.id}>{name(p.id)}</option>)}</select>}</div>{!allowed?<><p>完整决策记录在对局结束后开放，避免泄露身份和私有信息。</p><div className="wg-traces">{game.logs.filter(e=>!e.seatId).map(e=><p key={e.id}>{e.time?new Date(e.time).toLocaleTimeString('zh-CN'):''} · {e.text}</p>)}</div></>:<>{error&&<p role="alert">{error}</p>}<p>调用 {events.filter(e=>e.type==='model_started').length} 次 · 平均返回 {returned.length?(returned.reduce((n,e)=>n+(e.elapsedMs||0),0)/returned.length/1000).toFixed(1):'—'} 秒 · 失败 {events.filter(e=>e.type==='model_failed').length} · 超时 {events.filter(e=>e.type==='timeout').length}</p><div className="wg-record-tabs"><button aria-pressed={mode==='decisions'} onClick={()=>setMode('decisions')}>玩家决策</button><button aria-pressed={mode==='technical'} onClick={()=>setMode('technical')}>调用详情</button></div>{mode==='decisions'?<div className="wg-traces wg-decision-cards">{returned.filter(e=>(!seat||e.seatId===seat)&&events.some(t=>t.type==='action_accepted'&&t.requestId===e.requestId&&t.seq>e.seq)&&!events.some(t=>t.type==='model_failed'&&t.requestId===e.requestId&&t.attempt===e.attempt&&t.seq>e.seq)).reverse().map(e=><article className="wg-decision-card" key={e.seq}><header><strong>{name(e.seatId)}</strong><span>第 {e.day} {e.phase==='night'?'夜':'天'} · {kinds[e.kind||'']}</span><time>{new Date(e.time).toLocaleTimeString('zh-CN')}</time></header>{personalityView(e)}</article>)}{!returned.some(e=>(!seat||e.seatId===seat)&&events.some(t=>t.type==='action_accepted'&&t.requestId===e.requestId&&t.seq>e.seq))&&<p>暂无已生效的 AI 决策。请求进度和失败原因可在“调用详情”查看。</p>}</div>:<div className="wg-traces">{!events.length&&!error&&<p>暂无决策记录。旧版本对局的模型输入和耗时无法补录。</p>}{events.filter(e=>!seat||!e.seatId||e.seatId===seat).map(e=><details key={e.seq}><summary><time>{new Date(e.time).toLocaleTimeString('zh-CN')}</time> · {e.seatId?name(e.seatId)+' · ':''}{labels[e.type]}{e.kind?' · '+kinds[e.kind]:''}{e.elapsedMs!==undefined?' · '+(e.elapsedMs/1000).toFixed(1)+' 秒':''}</summary><div>第 {e.day} {e.phase==='night'?'夜':'天'} · {phases[e.phase]}{e.attempt&&e.attempt>1?' · 重试第 '+(e.attempt-1)+' 次':''}{e.model?' · '+e.model:''}</div>{detail(e)&&<p>{detail(e)}</p>}{e.action?.formatNote&&<p><b>格式兼容：</b>{e.action.formatNote}</p>}{e.metrics&&<p>HTTP {e.metrics.httpStatus} · 响应头 {(e.metrics.headersMs/1000).toFixed(1)} 秒 · 完整响应 {(e.metrics.totalMs/1000).toFixed(1)} 秒 · 结束原因 {e.metrics.finishReason||'未知'} · 输入 / 输出 / 推理 token：{e.metrics.inputTokens??'—'} / {e.metrics.outputTokens??'—'} / {e.metrics.reasoningTokens??'—'}</p>}{personalityView(e)}{e.type==='action_accepted'&&e.action&&<p><b>{e.kind==='wolf_plan'?'夜聊内容':'执行结果'}：</b>{actionText(e.action,e.kind)}</p>}{e.input&&inputView(e)}</details>)}</div>}</>}</section>;
}
