import {SettingsEmpty} from './SettingsWindow';
import {Select} from './Select';
import {useState} from 'react';
import Markdown from './MessageMarkdown';
import type {IntegrationSource,IntegrationsView,Skill} from './shared';
import {Icon} from './ui';
import {useI18n} from './i18n';

type Act=(operation:()=>Promise<unknown>)=>Promise<void>;
function Sources({sources,busy,act}:{sources:IntegrationSource[];busy:boolean;act:Act}){
  const {t}=useI18n();
  return <details className="integration-sources"><summary>{t('扫描位置与来源')} <span>{t('{count} 个可访问位置',{count:sources.filter(source=>source.exists).length})}</span><Icon name="down" size={15}/></summary>{sources.filter(source=>source.exists||source.label==='Aelion'||source.label==='共享技能').map(source=><div className="integration-source" key={source.id}><div><strong>{source.label}</strong><code>{source.path}</code>{source.issue&&<p>{source.issue}</p>}</div><span>{t('{count} 项',{count:source.count})}</span><button className="text-button" disabled={busy||!source.exists} onClick={()=>act(()=>window.aelion.openIntegrationPath({kind:'source',id:source.id}))}>{t('打开')}</button></div>)}</details>;
}
function SkillControls({skill,botId,onChanged}:{skill:Skill;botId:string;onChanged:()=>Promise<void>}){
  const {t,language}=useI18n();
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[versions,setVersions]=useState<Array<{revision:number;createdAt:string}>>([]),[revision,setRevision]=useState('');
  const manage=async(action:string)=>{setBusy(true);setError('');try{const result=await window.aelion.manageSkill({botId,id:skill.id,action,...(action==='restore_revision'?{revision:Number(revision)}:{})});if(action==='revisions')setVersions(result as typeof versions);else await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div><div className="settings-actions"><button className="text-button" disabled={busy} onClick={()=>void manage(skill.pinned?'unpin':'pin')}>{skill.pinned?t('取消置顶'):t('置顶')}</button><button className="text-button" disabled={busy} onClick={()=>void manage(skill.archived?'restore':'archive')}>{skill.archived?t('恢复'):t('归档')}</button>{skill.botId&&<button className="text-button" disabled={busy} onClick={()=>void manage('revisions')}>{t('历史版本')}</button>}</div>{Boolean(versions.length)&&<div className="settings-actions"><Select aria-label={t('技能历史版本')} value={revision} onChange={e=>setRevision(e.target.value)}><option value="">{t('选择版本')}</option>{versions.map(v=><option key={v.revision} value={v.revision}>{v.revision} · {new Date(v.createdAt).toLocaleString(language)}</option>)}</Select><button className="secondary-button" disabled={busy||revision===''} onClick={()=>void manage('restore_revision')}>{t('恢复此版本')}</button></div>}{error&&<p role="alert">{error}</p>}</div>;
}
function SkillEntry({skill,botId}:{skill:Skill;botId:string}){
  const {t}=useI18n();
  const [full,setFull]=useState<Skill>(),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);setError('');try{setFull(await window.aelion.readSkill({id:skill.id,botId}));}catch(error){setError((error as Error).message.replace(/^Error invoking remote method '[^']+': Error: /,''));}finally{setLoading(false);}};
  return <details className="settings-skill" onToggle={event=>{if(event.currentTarget.open)void load();}}><summary><Icon name="book" size={18}/><strong>{skill.name}</strong><span>{skill.botId?t('Bot 私有'):skill.source?.label||t('内置')}</span><Icon name="down" size={15}/></summary><p>{skill.description}</p><SkillControls skill={full||skill} botId={botId} onChanged={load}/>{skill.source&&<div className="skill-origin"><span>{skill.source.readonly?t('外部来源 · 只读'):t('SKILL.md 文件')}</span><code>{skill.source.path}</code></div>}{skill.compatibility&&<p className="subtle">{t('适用环境：{value}',{value:skill.compatibility})}</p>}{loading?<p className="subtle">{t('正在读取 SKILL.md…')}</p>:error?<p className="computer-notice">{error}</p>:<div className="markdown"><Markdown>{full?.body||skill.body}</Markdown>{Boolean(full?.availableFiles?.length)&&<details className="skill-files"><summary>{t('包内资源 · {count} 个文件',{count:full!.availableFiles!.length})}</summary><pre>{full!.availableFiles!.join('\n')}</pre></details>}</div>}</details>;
}
export function SkillsSettings({skills,botId,integrations,busy,act}:{skills:Skill[];botId:string;integrations?:IntegrationsView;busy:boolean;act:Act}){
  const {t}=useI18n();
  const [query,setQuery]=useState('');const filtered=skills.filter(skill=>`${skill.name} ${skill.description} ${skill.source?.label||''}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="integration-toolbar"><label className="integration-search"><Icon name="search" size={16}/><input placeholder={t('搜索技能或来源')} value={query} onChange={event=>setQuery(event.target.value)}/></label><button className="secondary-button" disabled={busy} onClick={()=>act(()=>window.aelion.refreshIntegrations())}>{t('重新扫描')}</button><button className="secondary-button" disabled={busy} onClick={()=>act(()=>window.aelion.addIntegrationSource('skills'))}>{t('添加目录')}</button></div>{integrations&&<div className="integration-path"><div><strong>{t('共享技能目录')}</strong><code>{integrations.sharedSkillDir}</code></div><button className="text-button" disabled={busy} onClick={()=>act(()=>window.aelion.openIntegrationPath({kind:'shared-skills'}))}>{t('打开目录')}</button></div>}<div className="skills-grid">{filtered.map(skill=><SkillEntry key={`${skill.id}:${integrations?.scannedAt}`} skill={skill} botId={botId}/>)}</div>{!filtered.length&&<SettingsEmpty icon="book" title={query?t('没有找到相关技能'):t('给伙伴添一点新本领')} description={query?t('试试其他关键词。'):t('添加技能目录，就可以在这里查看和管理。')}/>}</>;
}
export function McpSettings({integrations,busy,act}:{integrations?:IntegrationsView;busy:boolean;act:Act}){
  const {t}=useI18n();
  const [query,setQuery]=useState(''),[tests,setTests]=useState<Record<string,string>>({});
  if(!integrations)return <div className="settings-empty">{t('正在读取 MCP 配置…')}</div>;
  const labels={disabled:t('已发现 · 未启用'),available:t('等待使用'),connecting:t('连接中'),connected:t('已连接'),error:t('连接失败'),'needs-config':t('需要配置')};
  const servers=integrations.servers.filter(server=>`${server.name} ${server.source.label}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="integration-toolbar"><label className="integration-search"><Icon name="search" size={16}/><input placeholder={t('搜索 MCP 服务')} value={query} onChange={event=>setQuery(event.target.value)}/></label><button className="secondary-button" disabled={busy} onClick={()=>act(()=>window.aelion.refreshIntegrations())}>{t('重新扫描')}</button><button className="secondary-button" disabled={busy} onClick={()=>act(()=>window.aelion.addIntegrationSource('mcp'))}>{t('添加配置')}</button></div><div className="integration-path"><div><strong>{t('Aelion MCP 配置 · mcpServers')}</strong><code>{integrations.mcpFile}</code></div><button className="text-button" disabled={busy} onClick={()=>act(()=>window.aelion.openIntegrationPath({kind:'mcp-config'}))}>{t('打开配置')}</button></div><div className="mcp-list">{servers.map(server=><article className="mcp-card" key={server.id}><header><Icon name={server.transport==='stdio'?'terminal':'globe'} size={20}/><strong>{server.name}</strong><span className={`mcp-state ${server.status}`}>{labels[server.status]}{server.toolCount!==undefined?t(' · {count} 个工具',{count:server.toolCount}):''}</span></header><div className="mcp-source"><span>{server.source.label}</span><span>{server.transport.toUpperCase()}</span></div><p className="mcp-endpoint">{server.endpoint}</p><code>{server.source.path}</code>{server.issue&&<p className="computer-notice">{server.issue}</p>}{tests[server.id]&&<p className="mcp-test-result">{tests[server.id]}</p>}<footer><button className={server.enabled?'secondary-button':'primary-button'} disabled={busy||server.status==='needs-config'||server.status==='connecting'} onClick={()=>act(()=>window.aelion.setMcpEnabled({id:server.id,enabled:!server.enabled}))}>{server.enabled?t('停用'):t('启用')} {server.name}</button><button className="secondary-button" disabled={busy||!server.enabled||server.status==='needs-config'} onClick={()=>act(async()=>{setTests(value=>({...value,[server.id]:t('正在握手并读取工具目录…')}));try{const result=await window.aelion.testMcp(server.id);setTests(value=>({...value,[server.id]:t('握手成功：{count} 个工具{details}',{count:result.tools.length,details:result.tools.length?' · '+result.tools.slice(0,8).join('、'):''})}));}catch(error){setTests(value=>({...value,[server.id]:t('连接失败，请检查状态提示。')}));throw error;}})}>{t('测试连接')}</button><button className="text-button" disabled={busy} onClick={()=>act(()=>window.aelion.openIntegrationPath({kind:'source',id:server.id}))}>{t('查看来源')}</button></footer></article>)}</div>{!servers.length&&<SettingsEmpty icon="globe" title={query?t('没有找到相关服务'):t('连接更多工具')} description={query?t('试试其他关键词。'):t('添加 MCP 配置，让伙伴使用外部服务。')}/>}<Sources sources={integrations.sources.filter(source=>source.kind==='mcp')} busy={busy} act={act}/></>;
}
