import {useState} from 'react';
import Markdown from 'react-markdown';
import type {IntegrationSource,IntegrationsView,Skill} from './shared';
import {Icon} from './ui';

type Act=(operation:()=>Promise<unknown>)=>Promise<void>;
function Sources({sources,busy,act}:{sources:IntegrationSource[];busy:boolean;act:Act}){
  return <details className="integration-sources"><summary>扫描位置与来源 <span>{sources.filter(source=>source.exists).length} 个可访问位置</span><Icon name="down" size={15}/></summary>{sources.filter(source=>source.exists||source.label==='Aelion'||source.label==='共享技能').map(source=><div className="integration-source" key={source.id}><div><strong>{source.label}</strong><code>{source.path}</code>{source.issue&&<p>{source.issue}</p>}</div><span>{source.count} 项</span><button className="text-button" disabled={busy||!source.exists} onClick={()=>act(()=>window.aelion.openIntegrationPath({kind:'source',id:source.id}))}>打开</button></div>)}</details>;
}
function SkillEntry({skill,botId}:{skill:Skill;botId:string}){
  const [full,setFull]=useState<Skill>(),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);setError('');try{setFull(await window.aelion.readSkill({id:skill.id,botId}));}catch(error){setError((error as Error).message.replace(/^Error invoking remote method '[^']+': Error: /,''));}finally{setLoading(false);}};
  return <details className="settings-skill" onToggle={event=>{if(event.currentTarget.open)void load();}}><summary><Icon name="book" size={18}/><strong>{skill.name}</strong><span>{skill.botId?'Bot 私有':skill.source?.label||'内置'}</span><Icon name="down" size={15}/></summary><p>{skill.description}</p>{skill.source&&<div className="skill-origin"><span>{skill.source.readonly?'外部来源 · 只读':'SKILL.md 文件'}</span><code>{skill.source.path}</code></div>}{skill.compatibility&&<p className="subtle">适用环境：{skill.compatibility}</p>}{loading?<p className="subtle">正在读取 SKILL.md…</p>:error?<p className="computer-notice">{error}</p>:<div className="markdown"><Markdown>{full?.body||skill.body}</Markdown>{Boolean(full?.availableFiles?.length)&&<details className="skill-files"><summary>包内资源 · {full!.availableFiles!.length} 个文件</summary><pre>{full!.availableFiles!.join('\n')}</pre></details>}</div>}</details>;
}
export function SkillsSettings({skills,botId,integrations,busy,act}:{skills:Skill[];botId:string;integrations?:IntegrationsView;busy:boolean;act:Act}){
  const [query,setQuery]=useState('');const filtered=skills.filter(skill=>`${skill.name} ${skill.description} ${skill.source?.label||''}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="integration-toolbar"><label className="integration-search"><Icon name="search" size={16}/><input placeholder="搜索技能或来源" value={query} onChange={event=>setQuery(event.target.value)}/></label><button className="secondary-button" disabled={busy} onClick={()=>act(()=>window.aelion.refreshIntegrations())}>重新扫描</button><button className="secondary-button" disabled={busy} onClick={()=>act(()=>window.aelion.addIntegrationSource('skills'))}>添加目录</button></div>{integrations&&<div className="integration-path"><div><strong>共享技能目录</strong><code>{integrations.sharedSkillDir}</code></div><button className="text-button" disabled={busy} onClick={()=>act(()=>window.aelion.openIntegrationPath({kind:'shared-skills'}))}>打开目录</button></div>}<div className="skills-grid">{filtered.map(skill=><SkillEntry key={`${skill.id}:${integrations?.scannedAt}`} skill={skill} botId={botId}/>)}</div>{!filtered.length&&<div className="settings-empty">没有匹配的技能</div>}{integrations&&<Sources sources={integrations.sources.filter(source=>source.kind==='skills')} busy={busy} act={act}/>}</>;
}
export function McpSettings({integrations,busy,act}:{integrations?:IntegrationsView;busy:boolean;act:Act}){
  const [query,setQuery]=useState(''),[tests,setTests]=useState<Record<string,string>>({});
  if(!integrations)return <div className="settings-empty">正在读取 MCP 配置…</div>;
  const labels={disabled:'已发现 · 未启用',available:'等待使用',connecting:'连接中',connected:'已连接',error:'连接失败','needs-config':'需要配置'};
  const servers=integrations.servers.filter(server=>`${server.name} ${server.source.label}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="integration-toolbar"><label className="integration-search"><Icon name="search" size={16}/><input placeholder="搜索 MCP 服务" value={query} onChange={event=>setQuery(event.target.value)}/></label><button className="secondary-button" disabled={busy} onClick={()=>act(()=>window.aelion.refreshIntegrations())}>重新扫描</button><button className="secondary-button" disabled={busy} onClick={()=>act(()=>window.aelion.addIntegrationSource('mcp'))}>添加配置</button></div><div className="integration-path"><div><strong>Aelion MCP 配置 · mcpServers</strong><code>{integrations.mcpFile}</code></div><button className="text-button" disabled={busy} onClick={()=>act(()=>window.aelion.openIntegrationPath({kind:'mcp-config'}))}>打开配置</button></div><div className="mcp-list">{servers.map(server=><article className="mcp-card" key={server.id}><header><Icon name={server.transport==='stdio'?'terminal':'globe'} size={20}/><strong>{server.name}</strong><span className={`mcp-state ${server.status}`}>{labels[server.status]}{server.toolCount!==undefined?` · ${server.toolCount} 个工具`:''}</span></header><div className="mcp-source"><span>{server.source.label}</span><span>{server.transport.toUpperCase()}</span></div><p className="mcp-endpoint">{server.endpoint}</p><code>{server.source.path}</code>{server.issue&&<p className="computer-notice">{server.issue}</p>}{tests[server.id]&&<p className="mcp-test-result">{tests[server.id]}</p>}<footer><button className={server.enabled?'secondary-button':'primary-button'} disabled={busy||server.status==='needs-config'||server.status==='connecting'} onClick={()=>act(()=>window.aelion.setMcpEnabled({id:server.id,enabled:!server.enabled}))}>{server.enabled?'停用':'启用'} {server.name}</button><button className="secondary-button" disabled={busy||!server.enabled||server.status==='needs-config'} onClick={()=>act(async()=>{setTests(value=>({...value,[server.id]:'正在握手并读取工具目录…'}));try{const result=await window.aelion.testMcp(server.id);setTests(value=>({...value,[server.id]:`握手成功：${result.tools.length} 个工具${result.tools.length?' · '+result.tools.slice(0,8).join('、'):''}`}));}catch(error){setTests(value=>({...value,[server.id]:'连接失败，请检查状态提示。'}));throw error;}})}>测试连接</button><button className="text-button" disabled={busy} onClick={()=>act(()=>window.aelion.openIntegrationPath({kind:'source',id:server.id}))}>查看来源</button></footer></article>)}</div>{!servers.length&&<div className="settings-empty">没有匹配的 MCP 服务</div>}<Sources sources={integrations.sources.filter(source=>source.kind==='mcp')} busy={busy} act={act}/></>;
}
