import React from 'react';
import {createRoot} from 'react-dom/client';
import App from './App';
import './style.css';
import './settings.css';
import './typography.css';
import './theme.css';
import {initializeAppearance} from './use-appearance';
import {initializeI18n} from './i18n';
initializeAppearance();
void initializeI18n().catch(error=>console.error('Failed to initialize response language',error)).finally(()=>createRoot(document.getElementById('root')!).render(<App/>));
