import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import './preview-picker.css';
export interface PreviewOption{value:string;label:ReactNode;disabled?:boolean;}
export function previewMenuVisibility(open:boolean){if(!document.querySelector('.web-preview-slot'))return Promise.resolve();return new Promise<void>(resolve=>{const timer=setTimeout(resolve,1500);window.dispatchEvent(new CustomEvent('aelion-preview-menu',{detail:{open,done:()=>{clearTimeout(timer);resolve();}}}));});}
export function PreviewPicker({value,options,onChange,label,className='',disabled=false}:{value:string;options:PreviewOption[];onChange:(value:string)=>void;label:string;className?:string;disabled?:boolean}){
 const trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null),[open,setOpen]=useState(false),[position,setPosition]=useState({left:0,top:0,width:220}),generation=useRef(0);
 const close=()=>{generation.current++;setOpen(false);void previewMenuVisibility(false);};
 const show=async()=>{if(open){close();return;}const request=++generation.current;await previewMenuVisibility(true);if(request!==generation.current)return;const r=trigger.current!.getBoundingClientRect(),width=Math.max(210,Math.min(320,r.width));setPosition({left:Math.max(8,Math.min(r.left,innerWidth-width-8)),top:Math.min(r.bottom+5,innerHeight-150),width});setOpen(true);};
 useLayoutEffect(()=>{if(open){menu.current?.showPopover();requestAnimationFrame(()=>menu.current?.querySelector<HTMLElement>('[aria-selected=true]')?.focus());}},[open]);
 useEffect(()=>()=>{generation.current++;void previewMenuVisibility(false);},[]);
 useEffect(()=>{if(!open)return;const resize=()=>close();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[open]);
 return <><button ref={trigger} type="button" className={`preview-picker ${className} ${open?'is-open':''}`} disabled={disabled} aria-label={label} aria-haspopup="listbox" aria-expanded={open} onClick={()=>void show()} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();void show();}}}><span className="preview-picker-label">{options.find(o=>o.value===value)?.label||label}</span><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="m7 10 5 5 5-5"/></svg></button>{open&&createPortal(<div ref={menu} popover="auto" role="listbox" aria-label={label} className="preview-picker-popover" style={position} onToggle={e=>{if((e.nativeEvent as ToggleEvent).newState==='closed')close();}} onKeyDown={e=>{e.stopPropagation();const buttons=[...menu.current!.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')],at=buttons.indexOf(document.activeElement as HTMLButtonElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(at+(e.key==='ArrowDown'?1:buttons.length-1))%buttons.length]?.focus();}if(e.key==='Escape'){e.preventDefault();close();trigger.current?.focus();}}}>{options.map(option=><button key={option.value} type="button" role="option" disabled={option.disabled} aria-selected={option.value===value} onClick={()=>{onChange(option.value);close();trigger.current?.focus();}}><span>{option.label}</span>{option.value===value&&<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>}</button>)}</div>,document.body)}</>;
}

