export interface RuntimeSettings {maxTurns:number;maxMinutes:number;maxTokens:number;modelRetries:number;requestTimeoutMs:number;maxOutputTokens:number;parallelReads:number;fileCheckpoints:boolean;}
export const DEFAULT_RUNTIME:RuntimeSettings={maxTurns:0,maxMinutes:0,maxTokens:0,modelRetries:2,requestTimeoutMs:180000,maxOutputTokens:65536,parallelReads:4,fileCheckpoints:false};
export interface TaskStep {id:string;title:string;acceptance:string;status:'pending'|'working'|'done'|'skipped';evidenceIds:string[];note?:string;}
export interface TaskPlan {revision:number;goal:string;steps:TaskStep[];}
export interface ModelUsage {version?:2;inputTokens?:number;outputTokens?:number;totalTokens?:number;cachedTokens?:number;cacheWriteTokens?:number;reasoningTokens?:number;latencyMs?:number;attempts?:number;}
export interface RequestCacheDiagnostics {imageCount?:number;toolHistoryRepairs?:number;transport?:'http'|'websocket';incremental?:boolean;sentInputItems?:number;successfulPrefixMessages?:number;strictContinuation?:boolean;version:1;scopeFingerprint:string;optionsFingerprint:string;toolsFingerprint:string;inputFingerprint:string;inputBytes:number;inputMessages:number;compared:boolean;firstDifference:string;firstDifferentMessage?:number;firstDifferentRole?:string;sessionAffinitySent?:boolean;toolCount?:number;toolsAdded?:string[];toolsRemoved?:string[];toolsChanged?:string[];matchingPrefixMessages:number;matchingInputPrefixBytes:number;prefixScanTruncated:boolean;promptCacheKeySent:boolean;cacheKeyRejected?:boolean;}
export interface ContextUsage {estimateSource?:'tokenizer'|'usage-anchor';contextChanges?:string[];archivedImages?:number;estimatedTokens:number;calibration:number;prunedOutputs:number;epoch:number;}
export interface UsageRecord {context?:ContextUsage;estimatedTokens?:number;id:string;botId?:string;runId?:string;purpose:string;model:string;providerId?:string;providerName?:string;time:string;usage?:ModelUsage;requestCache?:RequestCacheDiagnostics;transportErrorCodes?:string[];error?:string;}
export function reportedTotal(usage?:ModelUsage){return usage?.totalTokens??(usage?.inputTokens!==undefined&&usage.outputTokens!==undefined?usage.inputTokens+usage.outputTokens:undefined);}
